def _generate_waft_html_template(
    header_html: str,
    main_html: str,
    title: str,
    timestamp: str,
    session_history: List[Dict[str, Any]] = None
) -> str:
    """Generate the full WAFT HTML template with all styling and JavaScript."""
    # Build session history HTML if provided
    session_history_html = ""
    if session_history:
        history_items = "\n".join([
            f'<li><a href=\'{item.get("file", "")}\' target=\'_blank\'>{item.get("date", "")}</a> - {item.get("file", "")}</li>'
            for item in session_history[:10]  # Limit to 10 most recent
        ])
        session_history_html = f"""
        <h2>Session History</h2>
        <div class="session-history">
            <p style="color: #999; font-size: 0.9em; margin-bottom: 0.5rem;">Previous show-me instances (click to view):</p>
            <ul class="history-list">
                {history_items}
            </ul>
        </div>
        """
    
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} | WAFT</title>
    <style>
        {css}
    </style>
</head>
<body>
    <!-- Above the Fold - Unified Top Section -->
    <section id="above-the-fold" class="above-the-fold">
        {nav}
        
        <!-- Header Section - Inside Above the Fold -->
        <div class="header-section-wrapper">
            {header_html}
        </div>
    </section>
    
    <main class="main-content">
        {main_html}
        {session_history_html}
        <footer class="footer">
            <p>Generated by WAFT (Wave Agent Framework & Tools) v0.9.2 | 2026-01-17 13:27:03</p>
        </footer>
    </main>
    
    <!-- Floating Oracle Button - Bottom Center -->
    <a href="oracle.html" target="_blank" class="btn-oracle">🔮 Consult the Oracle</a>
    <!-- Oracle Modal - CSS-only using :target -->
    <div class="modal" id="oracle-modal" role="dialog" aria-labelledby="oracle-title">
        <div class="modal-content">
            <div class="modal-header">
                <h2 id="oracle-title">🔮 Consult the Oracle</h2>
                <a href="#" class="modal-close" aria-label="Close modal">&times;</a>
            </div>
            <form action="http://localhost:8000/api/oracle/consult" method="POST" target="_blank">
                <div class="form-group">
                    <label for="oracle-question" class="form-label">Your Question:</label>
                    <textarea 
                        id="oracle-question" 
                        name="question" 
                        rows="4" 
                        class="form-textarea"
                        placeholder="Ask the Oracle anything about your project, code, or decisions..."
                        required
                    ></textarea>
                </div>
                <div class="form-actions">
                    <button type="submit" class="btn-primary">Consult (Opens in New Tab)</button>
                    <a href="#" class="btn-secondary">Cancel</a>
                </div>
            </form>
            <div style="margin-top: 1.5rem; padding: 1rem; background: #1f1f1f; border-radius: 6px; border: 1px solid #333333;">
                <p style="margin-bottom: 0.5rem; color: #d5d5d5; font-size: 0.9rem;"><strong style="color: #e5e5e5;">Alternative:</strong> Use the command line:</p>
                <pre style="margin: 0; background: #1a1a1a; padding: 0.75rem; border-radius: 4px;"><code>waft oracle "your question here"</code></pre>
            </div>
        </div>
    <!-- Toast Notification -->
    <div id="toast" class="toast-notification"></div>
    
    <!-- Minimal JavaScript for Copy/Save (graceful degradation) -->
    <script>
        
        // Wrap tables in scrollable container for horizontal scrolling on mobile
        (function() {
            document.querySelectorAll('table').forEach(table => {
                if (!table.parentElement.classList.contains('table-wrapper')) {
                    const wrapper = document.createElement('div');
                    wrapper.className = 'table-wrapper';
                    table.parentNode.insertBefore(wrapper, table);
                    wrapper.appendChild(table);
                }
            });
        })();
    

        // Show toast notification
        function showToast(message, duration = 2000) {
            const toast = document.getElementById('toast');
            toast.textContent = message;
            toast.classList.add('show');
            setTimeout(() => {
                toast.classList.remove('show');
            }, duration);
        }
        
        // Close dropdown after action
        function closeDropdowns() {
            window.location.hash = '';
        }
        
        // Copy HTML to clipboard
        async function copyHTML() {
            try {
                const html = document.documentElement.outerHTML;
                await navigator.clipboard.writeText(html);
                showToast('✅ HTML copied to clipboard!');
                closeDropdowns();
            } catch (err) {
                // Fallback: select text and prompt user to copy
                const textarea = document.createElement('textarea');
                textarea.value = document.documentElement.outerHTML;
                textarea.style.position = 'fixed';
                textarea.style.opacity = '0';
                document.body.appendChild(textarea);
                textarea.select();
                try {
                    document.execCommand('copy');
                    showToast('✅ HTML copied to clipboard!');
                } catch (e) {
                    showToast('❌ Copy failed. Use Save HTML instead.');
                }
                document.body.removeChild(textarea);
            }
        }
        
        // Copy text-only to clipboard
        async function copyText() {
            try {
                // Get all text content, preserving some structure
                const mainContent = document.querySelector('.main-content');
                const text = extractTextContent(mainContent);
                await navigator.clipboard.writeText(text);
                showToast('✅ Text copied to clipboard!');
                closeDropdowns();
            } catch (err) {
                // Fallback
                const textarea = document.createElement('textarea');
                const mainContent = document.querySelector('.main-content');
                textarea.value = extractTextContent(mainContent);
                textarea.style.position = 'fixed';
                textarea.style.opacity = '0';
                document.body.appendChild(textarea);
                textarea.select();
                try {
                    document.execCommand('copy');
                    showToast('✅ Text copied to clipboard!');
                } catch (e) {
                    showToast('❌ Copy failed. Use Save Text instead.');
                }
                document.body.removeChild(textarea);
            }
        }
        
        // Extract readable text content
        function extractTextContent(element) {
            let text = '';
            const walker = document.createTreeWalker(
                element,
                NodeFilter.SHOW_TEXT | NodeFilter.SHOW_ELEMENT,
                null,
                false
            );
            
            let node;
            while (node = walker.nextNode()) {
                if (node.nodeType === Node.TEXT_NODE) {
                    const content = node.textContent.trim();
                    if (content) {
                        text += content + '\n';
                    }
                } else if (node.nodeType === Node.ELEMENT_NODE) {
                    const tagName = node.tagName.toLowerCase();
                    if (['h1', 'h2', 'h3', 'h4', 'h5', 'h6'].includes(tagName)) {
                        text += '\n\n' + node.textContent.trim() + '\n';
                    } else if (tagName === 'p' || tagName === 'li') {
                        text += node.textContent.trim() + '\n';
                    } else if (tagName === 'tr') {
                        const cells = Array.from(node.querySelectorAll('td, th')).map(cell => cell.textContent.trim());
                        text += cells.join(' | ') + '\n';
                    }
                }
            }
            
            // Clean up excessive newlines
            return text.replace(/\n{3,}/g, '\n\n').trim();
        }
        
        // Save HTML as file
        function saveHTML() {
            const html = document.documentElement.outerHTML;
            const blob = new Blob([html], { type: 'text/html' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'waft-session-overview-' + new Date().toISOString().slice(0, 10) + '.html';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
            showToast('💾 HTML file saved!');
            closeDropdowns();
        }
        
        // Save text as file
        function saveText() {
            const mainContent = document.querySelector('.main-content');
            const text = extractTextContent(mainContent);
            const blob = new Blob([text], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'waft-session-overview-' + new Date().toISOString().slice(0, 10) + '.txt';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
            showToast('📝 Text file saved!');
            closeDropdowns();
        }
        
        // Keyboard shortcuts
        document.addEventListener('keydown', function(e) {
            // Ctrl/Cmd + Shift + H = Copy HTML
            if ((e.ctrlKey || e.metaKey) && e.shiftKey && e.key === 'H') {
                e.preventDefault();
                copyHTML();
            }
            // Ctrl/Cmd + Shift + T = Copy Text
            if ((e.ctrlKey || e.metaKey) && e.shiftKey && e.key === 'T') {
                e.preventDefault();
                copyText();
            }
            // Ctrl/Cmd + Shift + S = Save HTML
            if ((e.ctrlKey || e.metaKey) && e.shiftKey && e.key === 'S') {
                e.preventDefault();
                saveHTML();
            }
        });
        
        /* Copy Abstract Function */
        function copyAbstract() {
            const abstractBox = document.getElementById('abstract-content');
            if (!abstractBox) {
                console.error('Abstract content not found');
                return;
            }
            
            // Get text content, stripping HTML but preserving line breaks
            let text = abstractBox.innerText || abstractBox.textContent || '';
            
            // Clean up extra whitespace
            text = text.trim().replace(/\s+/g, ' ');
            
            // Copy to clipboard
            if (navigator.clipboard && navigator.clipboard.writeText) {
                navigator.clipboard.writeText(text).then(() => {
                    // Visual feedback
                    const btn = document.querySelector('.abstract-copy-btn');
                    if (btn) {
                        const originalHTML = btn.innerHTML;
                        btn.innerHTML = '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M13 4L6 11L3 8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
                        btn.style.color = '#8a9eff';
                        setTimeout(() => {
                            btn.innerHTML = originalHTML;
                            btn.style.color = '';
                        }, 1500);
                    }
                }).catch(err => {
                    console.error('Failed to copy:', err);
                });
            } else {
                // Fallback for older browsers
                const textArea = document.createElement('textarea');
                textArea.value = text;
                textArea.style.position = 'fixed';
                textArea.style.opacity = '0';
                document.body.appendChild(textArea);
                textArea.select();
                try {
                    document.execCommand('copy');
                    const btn = document.querySelector('.abstract-copy-btn');
                    if (btn) {
                        const originalHTML = btn.innerHTML;
                        btn.innerHTML = '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M13 4L6 11L3 8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
                        btn.style.color = '#8a9eff';
                        setTimeout(() => {
                            btn.innerHTML = originalHTML;
                            btn.style.color = '';
                        }, 1500);
                    }
                } catch (err) {
                    console.error('Fallback copy failed:', err);
                }
                document.body.removeChild(textArea);
            }
        }
        
        function copyRecommendedStep() {
            const actionEl = document.getElementById('recommended-action');
            const contextEl = document.getElementById('recommended-context');
            
            if (!actionEl) {
                console.error('Recommended action not found');
                return;
            }
            
            // Get action text
            let actionText = actionEl.innerText || actionEl.textContent || '';
            
            // Get context text (if available)
            let contextText = '';
            if (contextEl) {
                contextText = contextEl.innerText || contextEl.textContent || '';
            }
            
            // Combine action and context
            let combinedText = actionText.trim();
            if (contextText.trim()) {
                combinedText += '\n\n--- Context Primer ---\n' + contextText.trim();
            }
            
            // Copy to clipboard
            if (navigator.clipboard && navigator.clipboard.writeText) {
                navigator.clipboard.writeText(combinedText).then(() => {
                    // Visual feedback
                    const btn = document.querySelector('.recommended-copy-btn');
                    if (btn) {
                        const originalHTML = btn.innerHTML;
                        btn.innerHTML = '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M13 4L6 11L3 8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
                        btn.style.color = '#8a9eff';
                        setTimeout(() => {
                            btn.innerHTML = originalHTML;
                            btn.style.color = '';
                        }, 1500);
                    }
                }).catch(err => {
                    console.error('Failed to copy:', err);
                });
            } else {
                // Fallback for older browsers
                const textArea = document.createElement('textarea');
                textArea.value = combinedText;
                textArea.style.position = 'fixed';
                textArea.style.opacity = '0';
                document.body.appendChild(textArea);
                textArea.select();
                try {
                    document.execCommand('copy');
                    const btn = document.querySelector('.recommended-copy-btn');
                    if (btn) {
                        const originalHTML = btn.innerHTML;
                        btn.innerHTML = '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M13 4L6 11L3 8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
                        btn.style.color = '#8a9eff';
                        setTimeout(() => {
                            btn.innerHTML = originalHTML;
                            btn.style.color = '';
                        }, 1500);
                    }
                } catch (err) {
                    console.error('Fallback copy failed:', err);
                }
                document.body.removeChild(textArea);
            }
        }
    
    </script>
</body>
</html>"""
