"""
Celebrate - Generate and print celebratory PDFs!

Creates beautiful one-page celebration cards with creative design
and prints them to the material world.
"""

import platform
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

import markdown
from rich.console import Console


class CelebrateManager:
    """Manages celebration PDF generation and printing."""

    def __init__(self, project_path: Path):
        """
        Initialize celebrate manager.

        Args:
            project_path: Path to project root
        """
        self.project_path = project_path
        self.console = Console()

        # Celebration output directory
        self.celebrate_dir = project_path / "_pyrite" / "celebrations"
        self.celebrate_dir.mkdir(parents=True, exist_ok=True)

    def celebrate(
        self, achievement: str | None = None, message: str | None = None, print_pdf: bool = False
    ) -> Path | None:
        """
        Generate a one-page celebratory PDF card.

        Args:
            achievement: What was accomplished (optional)
            message: Custom celebration message (optional)
            print_pdf: Whether to print the PDF (default: False - use /print-PDF command instead)

        Returns:
            Path to generated PDF
        """
        self.console.print(
            "\n[bold cyan]🎉 Celebrate: Generating One-Page Celebration Card![/bold cyan]\n"
        )

        # Default achievement if not provided
        if not achievement:
            achievement = "A Moment Worth Celebrating!"

        # Default message if not provided
        if not message:
            message = "This is a moment of success, achievement, and joy! Take time to acknowledge what was accomplished and celebrate the win!"

        # Save markdown backup
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        timestamp_display = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        celebration_md = self.celebrate_dir / f"celebration_{timestamp}.md"
        celebration_md.write_text(
            f"# 🎉 Celebration: {achievement} 🎉\n\n**Date**: {timestamp_display}\n\n{message}\n"
        )

        # Generate PDF using new celebration card generator
        celebration_pdf = self.celebrate_dir / f"celebration_{timestamp}.pdf"

        try:
            # Add project root to path
            if str(self.project_path) not in sys.path:
                sys.path.insert(0, str(self.project_path))

            from src.waft.templates.celebration_card import generate_celebration_card

            # Generate one-page celebration card
            self.console.print("[yellow]→[/yellow] Creating beautiful one-page celebration card...")
            generated_path = generate_celebration_card(
                title=f"🎉 {achievement} 🎉",
                content="",
                output_path=celebration_pdf,
                achievement=achievement,
                message=message,
                subtitle="A Moment Worth Celebrating",
                date=timestamp_display,
                gratitude="Thank you to everyone who contributed to this achievement!",
                footer=f"Generated by WAFT • {datetime.now().strftime('%Y-%m-%d')}",
                page_numbers=True,
            )

            if generated_path and generated_path.exists():
                size = generated_path.stat().st_size / 1024  # KB
                self.console.print(f"[green]✓[/green] Celebration card generated: {generated_path}")
                self.console.print(f"[dim]   Size: {size:.1f} KB | One page guaranteed![/dim]")

                # Open PDF
                self.console.print("[yellow]→[/yellow] Opening celebration card...")
                import os

                system = platform.system()
                if system == "Darwin":  # macOS
                    subprocess.run(["open", str(generated_path)], check=False)
                elif system == "Windows":
                    os.startfile(str(generated_path))
                else:  # Linux
                    subprocess.run(["xdg-open", str(generated_path)], check=False)

                # Print PDF if explicitly requested (opt-in only)
                if print_pdf:
                    self.console.print(
                        "[yellow]→[/yellow] Printing celebration to material world..."
                    )
                    try:
                        result = subprocess.run(
                            ["lpr", str(generated_path)],
                            capture_output=True,
                            text=True,
                            check=False,
                        )
                        if result.returncode == 0:
                            self.console.print("[green]✓[/green] Celebration sent to printer! 🎉")
                        else:
                            self.console.print(
                                f"[yellow]⚠️[/yellow]  Print command returned: {result.stderr}"
                            )
                    except FileNotFoundError:
                        self.console.print(
                            f"[yellow]⚠️[/yellow]  'lpr' command not found. Please print manually: {generated_path}"
                        )
                    except Exception as e:
                        self.console.print(f"[yellow]⚠️[/yellow]  Print error: {e}")
                else:
                    # Show print command hint
                    self.console.print(
                        f"[dim]💡 To print: /print-PDF or lpr {generated_path}[/dim]"
                    )

                return generated_path

        except Exception as e:
            self.console.print(f"[yellow]⚠️[/yellow]  PDF generation failed: {e}")
            self.console.print(f"[dim]Markdown saved: {celebration_md}[/dim]")
            import traceback

            self.console.print(f"[dim]{traceback.format_exc()}[/dim]")
            return celebration_md

        return celebration_md if celebration_md.exists() else None

    def _create_celebration_content(
        self, achievement: str | None = None, message: str | None = None
    ) -> str:
        """Create celebration markdown content for card."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Default achievement if not provided
        if not achievement:
            achievement = "A Moment Worth Celebrating!"

        # Default message if not provided
        if not message:
            message = "This is a moment of success, achievement, and joy!"

        # Create simple markdown content for card
        # The card template will handle the beautiful formatting
        content = f"""
## What We Accomplished

{achievement}

## The Message

{message}

## Gratitude

Thank you to everyone who contributed to this achievement:
- The team for their dedication
- Collaborators for their support
- The process for its guidance
- The moment for its significance

## The Joy

This is a moment of pure joy and satisfaction! 🎉

Take time to acknowledge what was accomplished, feel the satisfaction of success, share the joy with others, build on this momentum, and celebrate the win!
"""
        return content

    def _extract_celebration_data(
        self, content: str, achievement: str | None = None, message: str | None = None
    ) -> dict[str, Any]:
        """Extract celebration data from content."""
        data = {
            "title": "",
            "subtitle": None,
            "achievement": achievement,
            "message": message,
            "date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "gratitude": None,
            "footer": None,
            "content": "",
        }

        lines = content.split("\n")

        # Extract title from first H1
        for line in lines:
            if line.startswith("# ") and not line.startswith("##"):
                data["title"] = line[2:].strip()
                break

        # Extract date
        for line in lines:
            if "**Date**:" in line or "**Date**:" in line:
                date_part = line.split(":", 1)[1].strip() if ":" in line else ""
                if date_part:
                    data["date"] = date_part
                break

        # Extract achievement section
        if not data["achievement"]:
            in_achievement = False
            achievement_lines = []
            for line in lines:
                line_stripped = line.strip()
                if "## What We Accomplished" in line_stripped or "## What We Accomplished" in line:
                    in_achievement = True
                    continue
                elif in_achievement:
                    if line_stripped.startswith("##") or line_stripped.startswith("---"):
                        break
                    if line_stripped and not line_stripped.startswith("*"):
                        achievement_lines.append(line_stripped)
            if achievement_lines:
                data["achievement"] = " ".join(achievement_lines[:3])  # First few lines

        # Extract message from abstract or message section
        if not data["message"]:
            in_message = False
            message_lines = []
            for line in lines:
                line_stripped = line.strip()
                if "## Abstract" in line_stripped or "## The Message" in line_stripped:
                    in_message = True
                    continue
                elif in_message:
                    if line_stripped.startswith("##") or line_stripped.startswith("---"):
                        break
                    if line_stripped:
                        message_lines.append(line_stripped)
            if message_lines:
                data["message"] = " ".join(message_lines[:5])  # First few lines

        # Extract gratitude
        in_gratitude = False
        gratitude_lines = []
        for line in lines:
            line_stripped = line.strip()
            if "## Gratitude" in line_stripped:
                in_gratitude = True
                continue
            elif in_gratitude:
                if line_stripped.startswith("##") or line_stripped.startswith("---"):
                    break
                if line_stripped and line_stripped.startswith("-"):
                    gratitude_lines.append(line_stripped.lstrip("- ").strip())
        if gratitude_lines:
            data["gratitude"] = " ".join(gratitude_lines[:3])

        # Default title if not found
        if not data["title"]:
            data["title"] = "🎉 Celebration! 🎉"

        return data

    def _extract_metadata_from_content(self, content: str) -> dict[str, Any]:
        """Extract metadata from celebration content."""
        metadata = {
            "title": "",
            "abstract": "",
            "authors": [],
            "affiliations": [],
            "email": None,
            "year": str(datetime.now().year),
            "references": [],
        }

        lines = content.split("\n")

        # Try to extract YAML frontmatter first
        frontmatter = {}
        if lines and lines[0].strip() == "---":
            i = 1
            current_key = None
            current_value = []
            while i < len(lines) and lines[i].strip() != "---":
                line = lines[i]
                line_stripped = line.strip()

                if (
                    ":" in line_stripped
                    and not line_stripped.startswith("-")
                    and not line_stripped.startswith(" ")
                ):
                    if current_key and current_value:
                        frontmatter[current_key] = (
                            "\n".join(current_value).strip().strip('"').strip("'")
                        )

                    key, value = line_stripped.split(":", 1)
                    current_key = key.strip().lower()
                    value_stripped = value.strip().strip('"').strip("'")
                    if value_stripped:
                        current_value = [value_stripped]
                    else:
                        current_value = []
                elif current_key:
                    if line_stripped.startswith("-") or line_stripped.startswith(" "):
                        current_value.append(
                            line_stripped.lstrip("- ").strip().strip('"').strip("'")
                        )
                    elif line_stripped:
                        current_value.append(line_stripped.strip().strip('"').strip("'"))

                i += 1

            if current_key and current_value:
                frontmatter[current_key] = "\n".join(current_value).strip().strip('"').strip("'")

        # Extract from frontmatter if available
        if frontmatter:
            metadata["title"] = frontmatter.get("title", "").strip().strip('"').strip("'")
            metadata["abstract"] = frontmatter.get("abstract", "").strip().strip('"').strip("'")

            if "authors" in frontmatter:
                authors_value = frontmatter["authors"]
                if isinstance(authors_value, str):
                    authors_list = [
                        a.strip() for a in re.split(r"[,\n]", authors_value) if a.strip()
                    ]
                    metadata["authors"] = [{"name": author} for author in authors_list]
                elif isinstance(authors_value, list):
                    metadata["authors"] = [
                        {"name": str(a).strip()} for a in authors_value if str(a).strip()
                    ]

            metadata["email"] = frontmatter.get("email", "").strip().strip('"').strip("'") or None
            year_value = frontmatter.get("year", "")
            if year_value:
                metadata["year"] = str(year_value).strip().strip('"').strip("'")

        # Extract from markdown structure if not in frontmatter
        if not metadata["title"]:
            for line in lines:
                if line.startswith("# ") and not line.startswith("##"):
                    metadata["title"] = line[2:].strip()
                    break

        if not metadata["abstract"]:
            in_abstract = False
            abstract_lines = []
            for line in lines:
                line_stripped = line.strip()
                if line_stripped.lower().startswith("## abstract"):
                    in_abstract = True
                    continue
                elif in_abstract:
                    if line_stripped.startswith("##") or line_stripped.startswith("---"):
                        break
                    if line_stripped:
                        abstract_lines.append(line_stripped)
            if abstract_lines:
                abstract_text = " ".join(abstract_lines)
                abstract_text = re.sub(r"\*\*([^*]+)\*\*", r"\1", abstract_text)
                abstract_text = re.sub(r"\*([^*]+)\*", r"\1", abstract_text)
                metadata["abstract"] = abstract_text

        # Default values
        if not metadata["title"]:
            metadata["title"] = "🎉 Celebration! 🎉"
        if not metadata["authors"]:
            metadata["authors"] = [{"name": "WAFT Team"}]

        return metadata

    def _process_markdown_to_html(self, content: str, metadata: dict[str, Any]) -> str:
        """Process markdown content to HTML."""
        lines = content.split("\n")
        processed_lines = []

        # Skip YAML frontmatter
        skip_frontmatter = False
        if lines and lines[0].strip() == "---":
            skip_frontmatter = True
            i = 1
            while i < len(lines) and lines[i].strip() != "---":
                i += 1
            if i < len(lines):
                i += 1
                lines = lines[i:]

        # Skip Abstract and References sections (handled by template)
        skip_abstract = False
        skip_references = False

        for line in lines:
            line_stripped = line.strip()
            line_lower = line_stripped.lower()

            # Skip Abstract section
            if line_lower.startswith("## abstract") or line_lower.startswith("# abstract"):
                skip_abstract = True
                continue
            elif skip_abstract:
                if (
                    line_stripped.startswith("##")
                    or line_stripped.startswith("# ")
                    or line_stripped.startswith("---")
                ):
                    skip_abstract = False
                    if not line_lower.startswith("## abstract") and not line_lower.startswith(
                        "# abstract"
                    ):
                        continue
                else:
                    continue

            # Skip References section
            if line_lower.startswith("## references") or line_lower.startswith("# references"):
                skip_references = True
                continue
            elif skip_references:
                if line_stripped.startswith("##") and not line_lower.startswith("## references"):
                    skip_references = False
                    continue
                elif line_stripped.startswith("# ") and not line_lower.startswith("# references"):
                    skip_references = False
                    continue
                else:
                    continue

            if skip_abstract or skip_references:
                continue

            processed_lines.append(line)

        # Convert markdown to HTML
        processed_md = "\n".join(processed_lines)
        html_content = markdown.markdown(
            processed_md,
            extensions=["fenced_code", "tables", "nl2br", "extra", "codehilite", "md_in_html"],
        )

        return html_content
