// ============================================================================
// WAFT TYPST TEMPLATE LIBRARY
// EXHAUSTIVE Menu of ALL Visualization Options
// ============================================================================

// ============================================================================
// PACKAGE IMPORTS - All packages we'll demonstrate
// ============================================================================

#import "@preview/tablex:0.0.9": tablex, cellx, rowspanx, colspanx
#import "@preview/gentle-clues:1.2.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, node, edge
#import "@preview/lilaq:0.5.0" as lq
#import "@preview/zero:0.5.0": num, zi
#import "@preview/diagraph:0.3.6": render as graphviz-render, raw-render as graphviz-raw
#import "@preview/pintorita:0.1.4"
#import "@preview/algorithmic:1.0.7"
#import algorithmic: algorithm, algorithm-figure, style-algorithm
#show: style-algorithm

// ============================================================================
// DOCUMENT SETUP
// ============================================================================

#set document(
  title: "WAFT Typst Template Library",
  author: "WAFT Documentation Team",
  date: datetime.today(),
)

#set page(
  paper: "us-letter",
  margin: (top: 0.6in, bottom: 0.6in, left: 0.6in, right: 0.6in),
  header: context {
    if counter(page).get().first() > 1 [
      #text(size: 8pt, fill: gray)[WAFT Typst Template Library]
      #h(1fr)
      #text(size: 8pt, fill: gray)[Page #counter(page).display()]
    ]
  },
)

#set text(font: "New Computer Modern", size: 9pt)
#set par(justify: true)
#set heading(numbering: "1.1")

// ============================================================================
// COVER PAGE
// ============================================================================

#align(center)[
  #v(0.8in)
  
  #rect(
    fill: gradient.linear(rgb("#1976d2"), rgb("#0d47a1"), angle: 135deg),
    width: 100%,
    inset: 40pt,
    radius: 12pt,
  )[
    #text(fill: white, size: 40pt, weight: "bold")[
      WAFT
    ]
    #v(0.1in)
    #text(fill: white, size: 20pt)[
      TYPST TEMPLATE LIBRARY
    ]
    #v(0.1in)
    #text(fill: white.darken(10%), size: 12pt)[
      Exhaustive Menu of ALL Visualization Options
    ]
  ]
  
  #v(0.3in)
  
  #grid(
    columns: (1fr, 1fr, 1fr, 1fr),
    gutter: 10pt,
    
    rect(fill: rgb("#e3f2fd"), inset: 12pt, radius: 4pt)[
      #align(center)[
        #text(size: 20pt, weight: "bold", fill: rgb("#1976d2"))[8+]
        #linebreak()
        #text(size: 8pt)[Packages]
      ]
    ],
    rect(fill: rgb("#e8f5e9"), inset: 12pt, radius: 4pt)[
      #align(center)[
        #text(size: 20pt, weight: "bold", fill: rgb("#4caf50"))[50+]
        #linebreak()
        #text(size: 8pt)[Examples]
      ]
    ],
    rect(fill: rgb("#fff3e0"), inset: 12pt, radius: 4pt)[
      #align(center)[
        #text(size: 20pt, weight: "bold", fill: rgb("#ff9800"))[10]
        #linebreak()
        #text(size: 8pt)[Categories]
      ]
    ],
    rect(fill: rgb("#fce4ec"), inset: 12pt, radius: 4pt)[
      #align(center)[
        #text(size: 20pt, weight: "bold", fill: rgb("#e91e63"))[100%]
        #linebreak()
        #text(size: 8pt)[Live]
      ]
    ],
  )
  
  #v(0.3in)
  
  #text(size: 10pt)[
    *Every example in this document is LIVE* — generated by the \
    actual Typst package, not screenshots or simulations.
  ]
  
  #v(0.2in)
  
  #rect(
    stroke: 1pt + gray,
    inset: 15pt,
    radius: 4pt,
    width: 90%,
  )[
    #text(size: 9pt)[
      *Packages Demonstrated:*
      gentle-clues • zero • lilaq • fletcher • tablex • diagraph • pintorita • algorithmic
    ]
  ]
]

#pagebreak()

// ============================================================================
// TABLE OF CONTENTS
// ============================================================================

#outline(
  title: [Table of Contents],
  indent: 2em,
  depth: 2,
)

#pagebreak()

// ============================================================================
// PART 1: CALLOUTS & ADMONITIONS
// ============================================================================

= Part 1: Callouts & Admonitions

#text(size: 8pt, fill: gray)[Package: `gentle-clues:1.2.0`]

== 1.1 Standard Callout Types

#info[*Info* — General information for readers.]

#success[*Success* — Confirmations and positive outcomes.]

#warning[*Warning* — Cautions about potential issues.]

#error[*Error* — Critical errors or failures.]

#tip[*Tip* — Helpful suggestions and best practices.]

#memo[*Memo* — Notes and reminders.]

#question[*Question* — Uncertainties or open questions.]

#example[*Example* — Demonstrations and illustrations.]

== 1.2 Callouts with Content

#info[
  *Multi-line Info Box*
  
  You can include:
  - Bullet points
  - *Bold text*
  - _Italic text_
  - `Code snippets`
]

#tip[
  *Code Example Inside Tip*
  
  ```python
  def hello():
      print("Hello WAFT!")
  ```
]

#pagebreak()

// ============================================================================
// PART 2: SCIENTIFIC NUMBERS
// ============================================================================

= Part 2: Scientific Number Formatting

#text(size: 8pt, fill: gray)[Package: `zero:0.5.0`]

== 2.1 Basic Number Formatting

#figure(
  tablex(
    columns: (1fr, 1fr, 1fr),
    align: (left, left, left),
    auto-vlines: false,
    
    cellx(fill: rgb("#e3f2fd"))[*Input*],
    cellx(fill: rgb("#e3f2fd"))[*Code*],
    cellx(fill: rgb("#e3f2fd"))[*Output*],
    
    [Large], [`#num[1234567]`], [#num[1234567]],
    [Decimal], [`#num[3.14159]`], [#num[3.14159]],
    [Scientific], [`#num[6.022e23]`], [#num[6.022e23]],
    [Negative exp], [`#num[1.38e-23]`], [#num[1.38e-23]],
    [Speed of light], [`#num[299792458]`], [#num[299792458]],
  ),
  caption: [Basic Number Formatting]
)

== 2.2 Uncertainties

#figure(
  tablex(
    columns: (1fr, 1fr),
    align: (left, left),
    auto-vlines: false,
    
    cellx(fill: rgb("#fff3e0"))[*Code*],
    cellx(fill: rgb("#fff3e0"))[*Output*],
    
    [`#num("9.81+-0.02")`], [#num("9.81+-0.02")],
    [`#num("1.602+-0.001e-19")`], [#num("1.602+-0.001e-19")],
    [`#num("2.998(1)e8")`], [#num("2.998(1)e8")],
    [`#num("42.0+-0.5")`], [#num("42.0+-0.5")],
  ),
  caption: [Numbers with Uncertainties]
)

== 2.3 Units (zi module)

#figure(
  tablex(
    columns: (auto, auto, auto),
    align: (left, left, left),
    auto-vlines: false,
    
    cellx(fill: rgb("#e8f5e9"))[*Quantity*],
    cellx(fill: rgb("#e8f5e9"))[*Code*],
    cellx(fill: rgb("#e8f5e9"))[*Output*],
    
    [Time], [`#zi.s[9.58]`], [#zi.s[9.58]],
    [Length], [`#zi.m[100]`], [#zi.m[100]],
    [Mass], [`#zi.kg[75.5]`], [#zi.kg[75.5]],
    [Frequency], [`#zi.Hz[440]`], [#zi.Hz[440]],
  ),
  caption: [Physical Units]
)

== 2.4 In-Context Usage

The speed of light is #num[299792458] m/s. Planck's constant is #num("6.626e-34") J·s.
Usain Bolt's 100m world record: #zi.s[9.58].

#pagebreak()

// ============================================================================
// PART 3: SCIENTIFIC PLOTTING
// ============================================================================

= Part 3: Scientific Plotting

#text(size: 8pt, fill: gray)[Package: `lilaq:0.5.0`]

== 3.1 Line Plots

=== Basic Line Plot

#align(center)[
  #lq.diagram(
    lq.plot((0, 1, 2, 3, 4, 5), (0, 1, 4, 9, 16, 25))
  )
]

=== Line Plot with Labels

#let xs = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
#let y1 = (0.1, 0.15, 0.25, 0.4, 0.55, 0.65, 0.72, 0.78, 0.82, 0.85, 0.87)
#let y2 = (0.05, 0.08, 0.12, 0.18, 0.25, 0.32, 0.40, 0.48, 0.55, 0.60, 0.64)

#align(center)[
  #lq.diagram(
    title: [Agent Fitness Over Generations],
    xlabel: [Generation],
    ylabel: [Fitness Score],
    lq.plot(xs, y1, label: [Best Agent]),
    lq.plot(xs, y2, label: [Average]),
  )
]

#pagebreak()

== 3.2 Scatter Plots

#let sx = (1, 2, 2.5, 3, 4, 4.5, 5, 6, 7, 8, 9, 10)
#let sy = (2.1, 3.5, 2.8, 5.2, 4.1, 6.3, 5.8, 7.2, 6.5, 8.1, 7.8, 9.2)

#align(center)[
  #lq.diagram(
    title: [Parameter Space Exploration],
    xlabel: [Learning Rate (×10⁻³)],
    ylabel: [Performance],
    lq.scatter(sx, sy),
  )
]

== 3.3 Bar Charts

#align(center)[
  #lq.diagram(
    title: [Component Completion Status],
    xlabel: [Component Index],
    ylabel: [Completion (%)],
    lq.bar((0, 1, 2, 3, 4, 5, 6, 7), (100, 95, 90, 90, 85, 50, 40, 0)),
  )
]

== 3.4 Multiple Series

#let epochs = (0, 1, 2, 3, 4, 5)
#let loss = (0.9, 0.7, 0.5, 0.35, 0.25, 0.2)
#let acc = (0.5, 0.65, 0.75, 0.82, 0.88, 0.91)
#let val = (0.4, 0.55, 0.68, 0.76, 0.81, 0.84)

#align(center)[
  #lq.diagram(
    title: [Training Metrics Comparison],
    xlabel: [Epoch],
    ylabel: [Value],
    lq.plot(epochs, loss, label: [Loss]),
    lq.plot(epochs, acc, label: [Accuracy]),
    lq.plot(epochs, val, label: [Validation]),
  )
]

#pagebreak()

// ============================================================================
// PART 4: NODE-EDGE DIAGRAMS
// ============================================================================

= Part 4: Node-Edge Diagrams (fletcher)

#text(size: 8pt, fill: gray)[Package: `fletcher:0.5.8`]

== 4.1 Simple Flowcharts

#align(center)[
  #diagram(
    node-stroke: 1pt,
    edge-stroke: 1pt,
    node((0, 0), [Input], shape: rect, fill: rgb("#e3f2fd")),
    edge("->"),
    node((1, 0), [Process], shape: rect, fill: rgb("#fff3e0")),
    edge("->"),
    node((2, 0), [Output], shape: rect, fill: rgb("#e8f5e9")),
  )
]

== 4.2 Vertical Flow

#align(center)[
  #diagram(
    node-stroke: 1pt,
    edge-stroke: 1pt,
    spacing: (10pt, 15pt),
    
    node((0, 0), [Start], shape: circle, fill: rgb("#c8e6c9")),
    edge((0, 0), (0, 1), "->"),
    node((0, 1), [Step 1], shape: rect, fill: rgb("#e3f2fd")),
    edge((0, 1), (0, 2), "->"),
    node((0, 2), [Step 2], shape: rect, fill: rgb("#e3f2fd")),
    edge((0, 2), (0, 3), "->"),
    node((0, 3), [End], shape: circle, fill: rgb("#ffcdd2")),
  )
]

== 4.3 Branching Decision Tree

#align(center)[
  #diagram(
    node-stroke: 1pt,
    edge-stroke: 1pt,
    spacing: (12pt, 20pt),
    
    node((1, 0), [Start], shape: circle, fill: rgb("#e8f5e9")),
    node((1, 1), [Condition?], shape: rect, fill: rgb("#fff3e0")),
    node((0, 2), [Path A], shape: rect, fill: rgb("#e3f2fd")),
    node((2, 2), [Path B], shape: rect, fill: rgb("#e3f2fd")),
    node((1, 3), [End], shape: circle, fill: rgb("#ffcdd2")),
    
    edge((1, 0), (1, 1), "->"),
    edge((1, 1), (0, 2), "->", label: "Yes"),
    edge((1, 1), (2, 2), "->", label: "No"),
    edge((0, 2), (1, 3), "->"),
    edge((2, 2), (1, 3), "->"),
  )
]

#pagebreak()

== 4.4 Multi-Agent Architecture

#align(center)[
  #diagram(
    node-stroke: 1pt,
    edge-stroke: 1pt,
    spacing: (15pt, 18pt),
    
    // User
    node((1, 0), [*User*], shape: circle, fill: rgb("#e8f5e9")),
    
    // Orchestrator
    node((1, 1), [*Orchestrator*], shape: rect, fill: rgb("#1976d2"), stroke: rgb("#1976d2")),
    
    // Agents
    node((0, 2), [Agent A], shape: rect, fill: rgb("#e3f2fd")),
    node((1, 2), [Agent B], shape: rect, fill: rgb("#e3f2fd")),
    node((2, 2), [Agent C], shape: rect, fill: rgb("#e3f2fd")),
    
    // Memory
    node((1, 3), [*Shared Memory*], shape: rect, fill: rgb("#fff3e0")),
    
    // Connections
    edge((1, 0), (1, 1), "<->"),
    edge((1, 1), (0, 2), "->"),
    edge((1, 1), (1, 2), "->"),
    edge((1, 1), (2, 2), "->"),
    edge((0, 2), (1, 3), "<->"),
    edge((1, 2), (1, 3), "<->"),
    edge((2, 2), (1, 3), "<->"),
  )
]

== 4.5 Data Pipeline

#align(center)[
  #diagram(
    node-stroke: 1pt,
    edge-stroke: 1pt,
    
    node((0, 0), [Raw Data], shape: rect, fill: rgb("#ffcdd2")),
    edge("->", label: "clean"),
    node((1, 0), [Cleaned], shape: rect, fill: rgb("#fff9c4")),
    edge("->", label: "transform"),
    node((2, 0), [Features], shape: rect, fill: rgb("#c8e6c9")),
    edge("->", label: "train"),
    node((3, 0), [Model], shape: rect, fill: rgb("#bbdefb")),
  )
]

== 4.6 WAFT Evolution Cycle

#align(center)[
  #diagram(
    node-stroke: 1pt,
    edge-stroke: 1pt,
    spacing: (18pt, 12pt),
    
    node((0, 0), [*Population*], shape: rect, fill: rgb("#e3f2fd")),
    edge("->", label: "evaluate"),
    node((1, 0), [*Fitness*], shape: rect, fill: rgb("#fff3e0")),
    edge("->", label: "select"),
    node((2, 0), [*Parents*], shape: rect, fill: rgb("#e8f5e9")),
    
    edge((2, 0), (2, 1), "->", label: "mutate"),
    node((2, 1), [*Offspring*], shape: rect, fill: rgb("#fce4ec")),
    edge((2, 1), (0, 1), "->", label: "replace"),
    node((0, 1), [*New Pop*], shape: rect, fill: rgb("#e3f2fd")),
    edge((0, 1), (0, 0), "->", label: "repeat"),
  )
]

#pagebreak()

// ============================================================================
// PART 5: GRAPHVIZ DIAGRAMS
// ============================================================================

= Part 5: Graphviz Diagrams (diagraph)

#text(size: 8pt, fill: gray)[Package: `diagraph:0.3.6`]

== 5.1 Simple Directed Graph

#align(center)[
  #graphviz-render("digraph { a -> b -> c; a -> c; }")
]

== 5.2 Labeled Graph

#align(center)[
  #graphviz-render("digraph G {
    rankdir=LR;
    A [label=\"Start\"];
    B [label=\"Process\"];
    C [label=\"End\"];
    A -> B [label=\"input\"];
    B -> C [label=\"output\"];
  }")
]

== 5.3 Styled Graph

#align(center)[
  #graphviz-render("digraph G {
    node [shape=box, style=filled, fillcolor=lightblue];
    edge [color=gray];
    
    User -> API;
    API -> Database;
    API -> Cache;
    Cache -> Database;
  }")
]

== 5.4 Cluster Subgraphs

#align(center)[
  #graphviz-render("digraph G {
    subgraph cluster_0 {
      label=\"Frontend\";
      style=filled;
      color=lightgrey;
      UI; Router; State;
    }
    subgraph cluster_1 {
      label=\"Backend\";
      style=filled;
      color=lightblue;
      API; DB; Cache;
    }
    UI -> API;
    State -> API;
  }")
]

#pagebreak()

== 5.5 Complex System Architecture

#align(center)[
  #graphviz-render("digraph WAFT {
    rankdir=TB;
    node [shape=box, style=\"rounded,filled\"];
    
    User [fillcolor=\"#e8f5e9\"];
    
    subgraph cluster_core {
      label=\"WAFT Core\";
      style=filled;
      color=\"#e3f2fd\";
      Orchestrator [fillcolor=\"#1976d2\", fontcolor=white];
      Genome [fillcolor=\"#bbdefb\"];
      Pantheon [fillcolor=\"#bbdefb\"];
      ScintGym [fillcolor=\"#bbdefb\"];
    }
    
    subgraph cluster_external {
      label=\"External\";
      style=filled;
      color=\"#fff3e0\";
      Empirica [fillcolor=\"#ffcc80\"];
      FlightRec [fillcolor=\"#ffcc80\"];
    }
    
    User -> Orchestrator;
    Orchestrator -> Genome;
    Orchestrator -> Pantheon;
    Orchestrator -> ScintGym;
    Genome -> Empirica;
    ScintGym -> FlightRec;
  }")
]

#pagebreak()

// ============================================================================
// PART 6: PINTORA DIAGRAMS
// ============================================================================

= Part 6: Pintora Diagrams (Mermaid-like)

#text(size: 8pt, fill: gray)[Package: `pintorita:0.1.4`]

== 6.1 Sequence Diagram

#align(center)[
  #pintorita.render("
sequenceDiagram
  User->>API: Request
  API->>Database: Query
  Database-->>API: Result
  API-->>User: Response
  ")
]

== 6.2 Entity Relationship Diagram

#align(center)[
  #pintorita.render("
erDiagram
  AGENT ||--o{ GENOME : has
  AGENT ||--o{ ACTION : performs
  GENOME ||--|{ GENE : contains
  ENVIRONMENT ||--o{ STATE : provides
  ")
]

== 6.3 Component Diagram

#align(center)[
  #pintorita.render("
componentDiagram
  [User Interface] --> [API Gateway]
  [API Gateway] --> [Agent Service]
  [API Gateway] --> [Genome Service]
  [Agent Service] --> [Database]
  [Genome Service] --> [Database]
  ")
]

#pagebreak()

== 6.4 Activity Diagram

#align(center)[
  #pintorita.render("
activityDiagram
  start
  :Initialize Population;
  :Evaluate Fitness;
  if (Termination?) then (yes)
    :Return Best;
    end
  else (no)
    :Select Parents;
    :Apply Mutation;
    :Create Offspring;
  endif
  ")
]

== 6.5 Mind Map

#align(center)[
  #pintorita.render("
mindmap
  + WAFT Framework
  ++ Core Components
  +++ Genome System
  +++ Pantheon
  +++ Scint Gym
  ++ External Tools
  +++ Empirica
  +++ Flight Recorder
  ++ Documentation
  +++ PDF Output
  +++ Wiki
  ")
]

#pagebreak()

// ============================================================================
// PART 7: ADVANCED TABLES
// ============================================================================

= Part 7: Advanced Tables (tablex)

#text(size: 8pt, fill: gray)[Package: `tablex:0.0.9`]

== 7.1 Styled Headers

#figure(
  tablex(
    columns: (auto, 1fr, auto, auto),
    align: (center, left, right, center),
    auto-vlines: false,
    
    cellx(fill: rgb("#1976d2"))[#text(fill: white, weight: "bold")[ID]],
    cellx(fill: rgb("#1976d2"))[#text(fill: white, weight: "bold")[Component]],
    cellx(fill: rgb("#1976d2"))[#text(fill: white, weight: "bold")[Status]],
    cellx(fill: rgb("#1976d2"))[#text(fill: white, weight: "bold")[✓]],
    
    [1], [Empirica Integration], [100%], [✅],
    [2], [Genome System], [95%], [✅],
    [3], [RPG Gym], [90%], [✅],
    [4], [Multi-Agent], [50%], [⚠️],
    [5], [Evolution Cycle], [0%], [❌],
  ),
  caption: [Styled Header Table]
)

== 7.2 Row and Column Spans

#figure(
  tablex(
    columns: (auto, auto, auto, auto),
    align: center,
    
    cellx(fill: rgb("#e3f2fd"), colspan: 4)[#text(weight: "bold")[WAFT Framework Components]],
    
    cellx(fill: rgb("#f5f5f5"), rowspan: 2)[*Core*],
    [Genome], [SHA-256], [✅],
    [Pantheon], [Beings], [✅],
    
    cellx(fill: rgb("#f5f5f5"), rowspan: 2)[*Tools*],
    [Empirica], [External], [✅],
    [Flight Rec], [Telemetry], [✅],
    
    cellx(fill: rgb("#f5f5f5"), rowspan: 2)[*Output*],
    [PDF], [Typst], [✅],
    [Wiki], [Markdown], [✅],
  ),
  caption: [Table with Row/Column Spans]
)

== 7.3 Progress Bars in Tables

#let progress(pct) = {
  let color = if pct >= 80 { rgb("#4caf50") } else if pct >= 40 { rgb("#ff9800") } else { rgb("#f44336") }
  box(width: 100%, height: 12pt, fill: rgb("#e0e0e0"), radius: 2pt,
    box(width: pct * 1%, height: 12pt, fill: color, radius: 2pt)
  )
}

#figure(
  tablex(
    columns: (1fr, 2fr, auto),
    align: (left, left, right),
    auto-vlines: false,
    
    cellx(fill: rgb("#e3f2fd"))[*Component*],
    cellx(fill: rgb("#e3f2fd"))[*Progress*],
    cellx(fill: rgb("#e3f2fd"))[*%*],
    
    [Empirica], [#progress(100)], [100%],
    [Genome], [#progress(95)], [95%],
    [RPG Gym], [#progress(90)], [90%],
    [Pantheon], [#progress(90)], [90%],
    [Flight Rec], [#progress(85)], [85%],
    [Multi-Agent], [#progress(50)], [50%],
    [Mutation], [#progress(40)], [40%],
    [Evo Cycle], [#progress(0)], [0%],
  ),
  caption: [Progress Visualization in Tables]
)

#pagebreak()

== 7.4 Alternating Row Colors

#figure(
  tablex(
    columns: (auto, 1fr, auto),
    align: (center, left, right),
    auto-vlines: false,
    
    cellx(fill: rgb("#1976d2"))[#text(fill: white)[*No.*]],
    cellx(fill: rgb("#1976d2"))[#text(fill: white)[*Description*]],
    cellx(fill: rgb("#1976d2"))[#text(fill: white)[*Value*]],
    
    cellx(fill: rgb("#f5f5f5"))[1], cellx(fill: rgb("#f5f5f5"))[Total lines added], cellx(fill: rgb("#f5f5f5"))[2,760+],
    [2], [Files created], [9],
    cellx(fill: rgb("#f5f5f5"))[3], cellx(fill: rgb("#f5f5f5"))[Wiki pages], cellx(fill: rgb("#f5f5f5"))[4],
    [4], [Git commits], [2],
    cellx(fill: rgb("#f5f5f5"))[5], cellx(fill: rgb("#f5f5f5"))[Packages used], cellx(fill: rgb("#f5f5f5"))[8],
  ),
  caption: [Alternating Row Colors]
)

== 7.5 Comparison Table

#figure(
  tablex(
    columns: (1fr, auto, auto, auto),
    align: (left, center, center, center),
    auto-vlines: false,
    
    cellx(fill: rgb("#e3f2fd"))[*Feature*],
    cellx(fill: rgb("#e3f2fd"))[*WAFT*],
    cellx(fill: rgb("#e3f2fd"))[*Traditional*],
    cellx(fill: rgb("#e3f2fd"))[*Diff*],
    
    [Epistemic Tracking], [✅], [❌], [+100%],
    [Genome Versioning], [✅], [❌], [+100%],
    [Multi-Agent], [⚠️], [❌], [+50%],
    [Evolution Cycle], [❌], [❌], [0%],
  ),
  caption: [Feature Comparison]
)

#pagebreak()

// ============================================================================
// PART 8: PSEUDOCODE
// ============================================================================

= Part 8: Algorithm Pseudocode

#text(size: 8pt, fill: gray)[Package: `algorithmic:1.0.7`]

== 8.1 Basic Algorithm

#algorithm-figure(
  [WAFT Evolution Loop],
  algorithm({
    import algorithmic: *
    
    Function("Evolve", ("population", "generations"), {
      For($i <= "generations"$, {
        Assign[$"fitness"$][$"Evaluate"("population")$]
        Assign[$"parents"$][$"Select"("population", "fitness")$]
        Assign[$"offspring"$][$"Mutate"("parents")$]
        Assign[$"population"$][$"Replace"("population", "offspring")$]
      })
      Return[$"BestIndividual"("population")$]
    })
  })
)

== 8.2 Conditional Logic

#algorithm-figure(
  [Fitness Evaluation],
  algorithm({
    import algorithmic: *
    
    Function("EvaluateFitness", ("agent", "environment"), {
      Assign[$"score"$][$0$]
      For([$"task" in "environment"$], {
        Assign[$"result"$][$"agent.Execute"("task")$]
        If($"result" = "success"$, {
          Assign[$"score"$][$"score" + 1$]
        })
        Else({
          Assign[$"score"$][$"score" - 0.5$]
        })
      })
      Return[$"score"$]
    })
  })
)

#pagebreak()

// ============================================================================
// PART 9: NATIVE TYPST FEATURES
// ============================================================================

= Part 9: Native Typst Features

== 9.1 Math Equations

=== Inline Math
The quadratic formula is $x = (-b plus.minus sqrt(b^2 - 4 a c)) / (2a)$.

=== Display Math
$ E = m c^2 $

$ integral_0^infinity e^(-x^2) d x = sqrt(pi) / 2 $

$ sum_(n=1)^infinity 1/n^2 = pi^2 / 6 $

=== Matrix
$ mat(
  1, 2, 3;
  4, 5, 6;
  7, 8, 9;
) $

== 9.2 Code Blocks

```python
def evolve(population, generations):
    for _ in range(generations):
        fitness = evaluate(population)
        parents = select(population, fitness)
        offspring = mutate(parents)
        population = replace(population, offspring)
    return best(population)
```

```rust
fn main() {
    let waft = WaftFramework::new();
    waft.evolve(100); // 100 generations
    println!("Best fitness: {}", waft.best_fitness());
}
```

== 9.3 Lists

=== Bullet List
- First item
- Second item
  - Nested item
  - Another nested
- Third item

=== Numbered List
+ Step one
+ Step two
+ Step three

=== Definition List
/ WAFT: Workbench for Agent Fitness Testing
/ Genome: Unique identifier and lineage tracker
/ Pantheon: Collection of entity archetypes

#pagebreak()

// ============================================================================
// PART 10: COMBINED EXAMPLES
// ============================================================================

= Part 10: Combined Examples

== 10.1 Complete Status Report

#info[
  *WAFT Framework Status Report* — January 24, 2026
]

#figure(
  tablex(
    columns: (auto, 1fr, auto, 2fr, auto),
    align: (center, left, center, left, center),
    auto-vlines: false,
    
    cellx(fill: rgb("#1976d2"))[#text(fill: white, size: 8pt, weight: "bold")[ID]],
    cellx(fill: rgb("#1976d2"))[#text(fill: white, size: 8pt, weight: "bold")[Component]],
    cellx(fill: rgb("#1976d2"))[#text(fill: white, size: 8pt, weight: "bold")[%]],
    cellx(fill: rgb("#1976d2"))[#text(fill: white, size: 8pt, weight: "bold")[Progress]],
    cellx(fill: rgb("#1976d2"))[#text(fill: white, size: 8pt, weight: "bold")[Status]],
    
    [1], [Empirica], [#num[100]], [#progress(100)], [✅],
    [2], [Genome], [#num[95]], [#progress(95)], [✅],
    [3], [RPG Gym], [#num[90]], [#progress(90)], [✅],
    [4], [Pantheon], [#num[90]], [#progress(90)], [✅],
    [5], [Flight Rec], [#num[85]], [#progress(85)], [✅],
    [6], [Multi-Agent], [#num[50]], [#progress(50)], [⚠️],
    [7], [Mutation], [#num[40]], [#progress(40)], [⚠️],
    [8], [Evo Cycle], [#num[0]], [#progress(0)], [❌],
  ),
  caption: [Complete WAFT Status with Numbers, Progress Bars, and Status Icons]
)

#v(0.2in)

#align(center)[
  #lq.diagram(
    title: [WAFT Component Completion],
    xlabel: [Component Index],
    ylabel: [Completion (%)],
    lq.bar((0, 1, 2, 3, 4, 5, 6, 7), (100, 95, 90, 90, 85, 50, 40, 0)),
  )
]

#pagebreak()

== 10.2 System Architecture + Flow

#align(center)[
  #graphviz-render("digraph WAFT {
    rankdir=TB;
    node [shape=box, style=\"rounded,filled\", fontsize=10];
    
    subgraph cluster_input {
      label=\"Input\";
      style=filled;
      color=\"#e8f5e9\";
      User [fillcolor=\"#c8e6c9\"];
    }
    
    subgraph cluster_core {
      label=\"WAFT Core\";
      style=filled;
      color=\"#e3f2fd\";
      Orchestrator [fillcolor=\"#1976d2\", fontcolor=white];
      Genome [fillcolor=\"#bbdefb\"];
      Pantheon [fillcolor=\"#bbdefb\"];
      ScintGym [fillcolor=\"#bbdefb\"];
    }
    
    subgraph cluster_external {
      label=\"External\";
      style=filled;
      color=\"#fff3e0\";
      Empirica [fillcolor=\"#ffcc80\"];
      FlightRec [fillcolor=\"#ffcc80\"];
    }
    
    subgraph cluster_output {
      label=\"Output\";
      style=filled;
      color=\"#fce4ec\";
      PDF [fillcolor=\"#f8bbd9\"];
      Wiki [fillcolor=\"#f8bbd9\"];
    }
    
    User -> Orchestrator;
    Orchestrator -> Genome;
    Orchestrator -> Pantheon;
    Orchestrator -> ScintGym;
    Genome -> Empirica;
    ScintGym -> FlightRec;
    Orchestrator -> PDF;
    Orchestrator -> Wiki;
  }")
]

#success[
  All diagrams, tables, charts, and visualizations above are generated by *real Typst packages*, not simulated.
]

#pagebreak()

// ============================================================================
// APPENDIX: IMPORT CHEATSHEET
// ============================================================================

= Appendix: Import Cheatsheet

== A.1 All Imports

```typst
// Callouts
#import "@preview/gentle-clues:1.2.0": *

// Scientific numbers and units
#import "@preview/zero:0.5.0": num, zi

// Scientific plotting
#import "@preview/lilaq:0.5.0" as lq

// Node-edge diagrams
#import "@preview/fletcher:0.5.8" as fletcher: diagram, node, edge

// Advanced tables
#import "@preview/tablex:0.0.9": tablex, cellx, rowspanx, colspanx

// Graphviz diagrams
#import "@preview/diagraph:0.3.6": render as graphviz-render

// Pintora (Mermaid-like) diagrams
#import "@preview/pintorita:0.1.4"

// Pseudocode
#import "@preview/algorithmic:1.0.7": algorithm, algorithm-figure
```

== A.2 Quick Reference

#figure(
  tablex(
    columns: (auto, 1fr, 1fr),
    align: (left, left, left),
    auto-vlines: false,
    
    cellx(fill: rgb("#1976d2"))[#text(fill: white, size: 8pt, weight: "bold")[Package]],
    cellx(fill: rgb("#1976d2"))[#text(fill: white, size: 8pt, weight: "bold")[Use For]],
    cellx(fill: rgb("#1976d2"))[#text(fill: white, size: 8pt, weight: "bold")[Key Function]],
    
    [`gentle-clues`], [Callouts], [`#info[]`, `#warning[]`],
    [`zero`], [Numbers/Units], [`#num[]`, `#zi.s[]`],
    [`lilaq`], [Plots], [`#lq.diagram()`, `#lq.plot()`],
    [`fletcher`], [Flowcharts], [`#diagram()`, `#node()`, `#edge()`],
    [`tablex`], [Tables], [`#tablex()`, `#cellx()`],
    [`diagraph`], [Graphviz], [`#graphviz-render()`],
    [`pintorita`], [Mermaid], [`#pintorita.render()`],
    [`algorithmic`], [Pseudocode], [`#algorithm-figure()`],
  ),
  caption: [Quick Reference Guide]
)

#v(0.5in)

#align(center)[
  #rect(fill: rgb("#1976d2"), inset: 20pt, radius: 8pt)[
    #text(fill: white, size: 14pt, weight: "bold")[
      WAFT Typst Template Library v1.0
    ]
    #linebreak()
    #text(fill: white.darken(10%), size: 10pt)[
      Every visualization is REAL. Copy and use.
    ]
  ]
]

#align(center)[
  #text(size: 8pt, fill: gray)[
    Generated: #datetime.today().display() | Source: Typst Universe
  ]
]
