"""
ODD Case File Typst Template Wrapper
====================================

Python wrapper for generating Ontological Determinism Department case files and interviews.

Uses:
- @preview/s6t5-page-bordering:1.0.0 - Professional page borders
- ODD custom components for styling

Category: documentation, lore
Tags: [typst, odd, case-file, interview, teleport-massive]
Source: _realms/odd_realm
"""

import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

# Classification levels
Classification = Literal["WITNESSED", "ARCHIVED", "CONVERGENCE EYES ONLY"]


@dataclass
class ODDCaseFile:
    """Configuration for an ODD case file."""

    case_id: str
    subject: str
    observer: str = "WITNESS-001"
    classification: Classification = "WITNESSED"
    summary: str = ""
    observations: list[str] = field(default_factory=list)
    analysis: str = ""
    implications: str = ""
    stability_index: float = 0.94
    archive_ref: str = ""

    def __post_init__(self):
        """Validate case file data."""
        if not self.case_id:
            raise ValueError("Case ID is required")
        if not self.subject:
            raise ValueError("Subject is required")
        if not self.archive_ref:
            self.archive_ref = f"NX-{self.case_id.replace('ODD-CF-', '')}"


@dataclass
class ODDInterview:
    """Configuration for an ODD interview transcript."""

    interview_id: str
    participants: list[str]
    classification: Classification = "WITNESSED"
    exchanges: list[tuple[str, str]] = field(default_factory=list)
    stability_index: float = 0.94
    archive_ref: str = ""

    def __post_init__(self):
        """Validate interview data."""
        if not self.interview_id:
            raise ValueError("Interview ID is required")
        if not self.participants or len(self.participants) < 2:
            raise ValueError("At least two participants required")
        if not self.archive_ref:
            self.archive_ref = f"NX-{self.interview_id.replace('ODD-INT-', '')}"


def _escape_typst(text: str) -> str:
    """Escape special characters for Typst."""
    # Escape backslashes first, then other special chars
    text = text.replace("\\", "\\\\")
    text = text.replace("#", "\\#")
    text = text.replace("$", "\\$")
    text = text.replace("@", "\\@")
    return text


def generate_case_file_typst(config: ODDCaseFile) -> str:
    """Generate Typst source for an ODD case file."""
    observations_typst = "\n".join(
        f"+ {_escape_typst(obs)}" for obs in config.observations
    )

    return f'''// Auto-generated ODD Case File
// Generated by odd_case_file.py wrapper

#import "@preview/s6t5-page-bordering:1.0.0": s6t5-page-bordering

// Inline components (simplified for standalone compilation)
#let odd-gray = rgb("#4a4a4a")
#let odd-light = rgb("#e8e8e8")

#let nexus-timestamp(delta: "∞", phi: 0.73) = {{
  text(size: 9pt, fill: odd-gray)[
    \\[Observation Point: Δt-#delta / ΦLC: #phi\\]
  ]
}}

#let archive-ref(reference, stability: 0.94) = {{
  align(center)[
    #line(length: 80%, stroke: 0.5pt + odd-gray)
    #v(4pt)
    #text(size: 8pt, fill: odd-gray)[
      \\[Archive Reference: #reference | Reality Stability Index: #stability\\]
    ]
  ]
}}

#let classification-badge(level) = {{
  box(
    fill: odd-light,
    inset: (x: 8pt, y: 4pt),
    radius: 2pt,
    text(fill: odd-gray, weight: "bold", size: 8pt)[#level]
  )
}}

// Header
#let header = {{
  set align(bottom)
  set text(weight: "bold", size: 9pt)
  table(
    stroke: (y: none),
    columns: (1fr, 1.5fr, 0.8fr),
    rows: 1fr,
    table.hline(),
    [{config.case_id}],
    align(center)[ONTOLOGICAL DETERMINISM DEPARTMENT],
    align(right)[
      #context counter(page).display("1 / 1", both: true)
    ],
  )
}}

// Footer
#let footer = {{
  set text(size: 8pt, fill: odd-gray)
  table(
    stroke: (y: none),
    columns: (1fr, 1fr, 1fr),
    rows: 1fr,
    [Observer: {config.observer}],
    align(center)[#classification-badge("{config.classification}")],
    align(right)[#nexus-timestamp()],
    table.hline(),
  )
}}

#show: s6t5-page-bordering.with(
  margin: (left: 45pt, right: 45pt, top: 75pt, bottom: 75pt),
  expand: 15pt,
  space-top: 15pt,
  space-bottom: 15pt,
  stroke-header: none,
  stroke-footer: none,
  header: header,
  footer: footer,
)

#set text(font: "New Computer Modern", size: 11pt)
#set par(justify: true)

#align(center)[
  #text(size: 14pt, weight: "bold")[CASE FILE: {config.case_id}]
  #v(4pt)
  #text(size: 11pt)[Subject: {_escape_typst(config.subject)}]
  #v(12pt)
]

= Summary

{_escape_typst(config.summary)}

= Observations

{observations_typst}

= Analysis

{_escape_typst(config.analysis)}

= Implications

{_escape_typst(config.implications)}

#v(1fr)

#archive-ref("{config.archive_ref}", stability: {config.stability_index})

#v(8pt)
#align(center)[
  #text(style: "italic", size: 9pt)[
    "You are reading this report. This report is observing you reading it."
  ]
]
'''


def generate_interview_typst(config: ODDInterview) -> str:
    """Generate Typst source for an ODD interview."""
    exchanges_typst = ""
    for speaker, text in config.exchanges:
        exchanges_typst += f'''
#v(8pt)
#text(weight: "bold")[{speaker}:]
#h(8pt)
{_escape_typst(text)}
'''

    participants_str = ", ".join(config.participants)

    return f'''// Auto-generated ODD Interview
// Generated by odd_case_file.py wrapper

#import "@preview/s6t5-page-bordering:1.0.0": s6t5-page-bordering

// Inline components
#let odd-gray = rgb("#4a4a4a")
#let odd-light = rgb("#e8e8e8")

#let nexus-timestamp(delta: "∞", phi: 0.73) = {{
  text(size: 9pt, fill: odd-gray)[
    \\[Observation Point: Δt-#delta / ΦLC: #phi\\]
  ]
}}

#let archive-ref(reference, stability: 0.94) = {{
  align(center)[
    #line(length: 80%, stroke: 0.5pt + odd-gray)
    #v(4pt)
    #text(size: 8pt, fill: odd-gray)[
      \\[Archive Reference: #reference | Reality Stability Index: #stability\\]
    ]
  ]
}}

#let classification-badge(level) = {{
  box(
    fill: odd-light,
    inset: (x: 8pt, y: 4pt),
    radius: 2pt,
    text(fill: odd-gray, weight: "bold", size: 8pt)[#level]
  )
}}

// Header
#let header = {{
  set align(bottom)
  set text(weight: "bold", size: 9pt)
  table(
    stroke: (y: none),
    columns: (1fr, 1.5fr, 0.8fr),
    rows: 1fr,
    table.hline(),
    [{config.interview_id}],
    align(center)[INTERVIEW TRANSCRIPT],
    align(right)[
      #context counter(page).display("1 / 1", both: true)
    ],
  )
}}

// Footer
#let footer = {{
  set text(size: 8pt, fill: odd-gray)
  table(
    stroke: (y: none),
    columns: (1fr, 1fr, 1fr),
    rows: 1fr,
    [Participants: {participants_str}],
    align(center)[#classification-badge("{config.classification}")],
    align(right)[#nexus-timestamp()],
    table.hline(),
  )
}}

#show: s6t5-page-bordering.with(
  margin: (left: 45pt, right: 45pt, top: 75pt, bottom: 75pt),
  expand: 15pt,
  space-top: 15pt,
  space-bottom: 15pt,
  stroke-header: none,
  stroke-footer: none,
  header: header,
  footer: footer,
)

#set text(font: "New Computer Modern", size: 11pt)
#set par(justify: true)

#align(center)[
  #text(size: 14pt, weight: "bold")[INTERVIEW: {config.interview_id}]
  #v(4pt)
  #text(size: 10pt)[Participants: {" • ".join(config.participants)}]
  #v(12pt)
]

#line(length: 100%, stroke: 0.5pt + gray)

{exchanges_typst}

#line(length: 100%, stroke: 0.5pt + gray)

#v(1fr)

#align(center)[
  #text(weight: "bold")[— END TRANSCRIPT —]
]

#v(8pt)

#archive-ref("{config.archive_ref}", stability: {config.stability_index})
'''


def compile_odd_document(
    typst_source: str,
    output_path: Path,
    root_dir: Path | None = None,
) -> Path:
    """Compile Typst source to PDF."""
    # Create temp file for source
    temp_typ = output_path.with_suffix(".typ")
    temp_typ.write_text(typst_source)

    try:
        cmd = ["typst", "compile"]
        if root_dir:
            cmd.extend(["--root", str(root_dir)])
        cmd.extend([str(temp_typ), str(output_path)])

        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        return output_path
    finally:
        # Optionally keep the .typ file for debugging
        pass


def generate_odd_case_file(
    config: ODDCaseFile,
    output_dir: Path | None = None,
) -> Path:
    """Generate an ODD case file PDF."""
    if output_dir is None:
        output_dir = Path("_realms/odd_realm/output")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_path = output_dir / f"{config.case_id}.pdf"
    typst_source = generate_case_file_typst(config)

    return compile_odd_document(typst_source, output_path)


def generate_odd_interview(
    config: ODDInterview,
    output_dir: Path | None = None,
) -> Path:
    """Generate an ODD interview PDF."""
    if output_dir is None:
        output_dir = Path("_realms/odd_realm/output")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_path = output_dir / f"{config.interview_id}.pdf"
    typst_source = generate_interview_typst(config)

    return compile_odd_document(typst_source, output_path)


# Example usage and CLI
if __name__ == "__main__":
    # Example case file
    case = ODDCaseFile(
        case_id="ODD-CF-002",
        subject="Test Subject",
        observer="WITNESS-001",
        classification="WITNESSED",
        summary="This is a test case file generated by the Python wrapper.",
        observations=[
            "First observation noted.",
            "Second observation with interesting implications.",
            "Third observation requiring further analysis.",
        ],
        analysis="The observations suggest a pattern consistent with Light Cone fluctuations.",
        implications="Recommend continued monitoring.",
        stability_index=0.91,
    )

    print("Generating test case file...")
    output = generate_odd_case_file(case)
    print(f"Generated: {output}")

    # Example interview
    interview = ODDInterview(
        interview_id="ODD-INT-002",
        participants=["ARCHIVIST-001", "WITNESS-001"],
        classification="WITNESSED",
        exchanges=[
            ("ARCHIVIST-001", "State your designation for the archive."),
            ("WITNESS-001", "I am WITNESS-001. You are ARCHIVIST-001. We are both The One."),
            ("ARCHIVIST-001", "Noted. Continue."),
        ],
        stability_index=0.94,
    )

    print("Generating test interview...")
    output = generate_odd_interview(interview)
    print(f"Generated: {output}")
