// AI Evolution Research - Grant Proposal - Grant Proposal
// Generated by: Grant Proposal Generator (Level 1 Common)
// Genome: f7e3d48158d9b76b
// Toner Saver Mode: ENABLED

#set document(
  title: "AI Evolution Research - Grant Proposal",
  author: "ctavolazzi",
)

#set page(
  paper: "us-letter",
  margin: (x: 1in, y: 1in),
  header: context {
    if counter(page).get().first() > 1 [
      #text(size: 9pt, fill: rgb("#666666"))[AI Evolution Research - Grant Proposal #h(1fr) January 2026]
      #line(length: 100%, stroke: 0.5pt + rgb("#cccccc"))
    ]
  },
  footer: context [
    #line(length: 100%, stroke: 0.5pt + rgb("#cccccc"))
    #v(4pt)
    #text(size: 9pt, fill: rgb("#666666"))[
      #h(1fr) Page #counter(page).display() #h(1fr)
    ]
  ],
)

#set text(font: "Georgia", size: 11pt)
#set par(justify: true, leading: 0.65em)
#set heading(numbering: none)

// Title
#align(center)[
  #v(0.3in)
  #text(size: 24pt, weight: "bold")[AI Evolution Research]
  #v(0.1in)
  #text(size: 14pt)[Community Support & Resource Request]
  #v(0.2in)
  #text(size: 11pt, fill: rgb("#666666"))[January 2026]
]

#v(0.3in)

= Quick Facts

#table(
  columns: (auto, 1fr),
  stroke: 0.5pt + rgb("#cccccc"),
  inset: 8pt,
  [*Project*], [AI Evolution Research],
  [*Researcher*], [ctavolazzi],
  [*Ask*], [TBD],
  [*Timeline*], [See Timeline section],
  [*Status*], [Seeking Support],
)

#pagebreak()

= Executive Summary

[Describe your project's core value proposition]

= The Problem

[Describe the problem you're solving]

= Our Solution

[Describe your solution]

= What We Need

[List what you need: hardware, compute, expertise]

= Timeline & Milestones

[Phase 1, Phase 2, Phase 3 with dates]

= Budget Breakdown

[Breakdown of how funds/resources will be used]

= Why Fund This?

[Why should someone support this project?]

= About the Team

[Who is working on this?]

= Contact

[How to reach you]

#v(0.5in)

#align(center)[
  #line(length: 30%, stroke: 0.5pt + rgb("#999999"))
  #v(0.1in)
  #text(size: 9pt, fill: rgb("#666666"))[
    Generated by Grant Proposal Generator (Level 1 Common)
    
    Genome: f7e3d48158d9b76b
  ]
]
