#!/usr/bin/env python3
"""
WAFT Advanced Demonstration
===========================

This advanced demo showcases WAFT's powerful self-documentation and organization capabilities:

1. Framework Self-Documentation - WAFT inspects itself and generates documentation
2. PDF Binder Organization - Recursive scanning and intelligent booklet assembly
3. Meta-Cognitive Integration - Combining tools with epistemic memory

This demonstrates WAFT's recursive self-improvement through documentation.
"""

import sys
import subprocess
import platform
from pathlib import Path
from datetime import datetime
from typing import Optional

# Add project root to path
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn

console = Console()


# ============================================================================
# Utility Functions
# ============================================================================

def open_file(file_path: Path) -> bool:
    """Open a file using the system's default application."""
    try:
        system = platform.system()
        if system == "Darwin":  # macOS
            subprocess.run(["open", str(file_path)], check=True)
        elif system == "Windows":
            subprocess.run(["start", str(file_path)], shell=True, check=True)
        else:  # Linux
            subprocess.run(["xdg-open", str(file_path)], check=True)
        return True
    except Exception:
        return False


# ============================================================================
# Demo Sections
# ============================================================================

def welcome_message():
    """Display welcome message."""
    console.print("\n" + "=" * 80)
    console.print(Panel.fit(
        "[bold cyan]WAFT Advanced Demonstration[/bold cyan]\n\n"
        "[yellow]World Architecture Framework & Templates[/yellow]\n\n"
        "This demo showcases WAFT's advanced capabilities:\n"
        "• Self-Documentation (WAFT inspecting itself)\n"
        "• PDF Organization (Intelligent booklet assembly)\n"
        "• Meta-Cognitive Integration",
        title="Welcome",
        border_style="cyan"
    ))
    console.print("=" * 80)
    console.print()


def demonstrate_framework_documentation(demo_dir: Path) -> Path:
    """Demonstrate WAFT's self-documentation capability."""
    console.print("\n[bold cyan]📚 DEMONSTRATION 1: FRAMEWORK SELF-DOCUMENTATION[/bold cyan]\n")
    
    console.print("WAFT can inspect its own codebase and generate comprehensive")
    console.print("documentation about how it functions. This is [bold]recursive[/bold]")
    console.print("self-documentation - the system describing itself.\n")
    
    console.print("[dim]Running framework documentation generator...[/dim]\n")
    
    # Import and run framework documentation generator
    sys.path.insert(0, str(project_root / "tools" / "framework_documentation"))
    from generate_framework_docs import generate_framework_documentation
    
    framework_doc_path = demo_dir / "WAFT_Framework_Documentation.pdf"
    
    try:
        with console.status("[bold cyan]WAFT is inspecting itself...[/bold cyan]"):
            result = generate_framework_documentation(project_root, framework_doc_path)
        
        if result and result.exists():
            size_mb = result.stat().st_size / (1024 * 1024)
            console.print(f"  [green]✅[/green] Framework documentation generated")
            console.print(f"     File: [bold]{result.name}[/bold]")
            console.print(f"     Size: [bold]{size_mb:.2f} MB[/bold]")
            console.print()
            console.print("  [cyan]💡[/cyan] This documentation was generated by WAFT scanning")
            console.print("     its own codebase - no content is hardcoded!")
            console.print()
            return result
        else:
            console.print("  [yellow]⚠️[/yellow]  Documentation generation completed but file not found")
            return None
    except Exception as e:
        console.print(f"  [red]❌[/red] Error: {e}")
        import traceback
        console.print(f"     [dim]{traceback.format_exc()}[/dim]")
        return None


def demonstrate_pdf_organization(demo_dir: Path) -> Optional[Path]:
    """Demonstrate PDF binder organization."""
    console.print("\n[bold cyan]📦 DEMONSTRATION 2: PDF BINDER ORGANIZATION[/bold cyan]\n")
    
    console.print("WAFT can recursively scan any directory, find all PDFs,")
    console.print("extract metadata, and organize them into intelligent booklets.\n")
    
    # Check if we have PDFs in the project to organize
    pdf_count = len(list(project_root.rglob("*.pdf")))
    
    if pdf_count == 0:
        console.print("  [yellow]⚠️[/yellow]  No PDFs found in project to organize")
        console.print("     Creating a sample demonstration instead...\n")
        return None
    
    console.print(f"  [cyan]🔍[/cyan] Found [bold]{pdf_count}[/bold] PDF files in project")
    console.print("     Organizing into booklets (max 25 pages each)...\n")
    
    # Import and run PDF organizer
    sys.path.insert(0, str(project_root / "tools" / "pdf_binder_organizer"))
    from organize_pdfs import PDFBinderOrganizer
    
    output_dir = demo_dir / "organized_pdfs"
    output_dir.mkdir(exist_ok=True)
    
    try:
        organizer = PDFBinderOrganizer(project_root, output_dir)
        
        # Run organization
        result = organizer.organize()
        
        if result:
            console.print()
            console.print("  [green]✅[/green] PDF organization complete!")
            console.print(f"     Output: [bold]{output_dir}[/bold]")
            console.print()
            
            # Show what was created
            full_binder = output_dir / "FULL_BINDER.pdf"
            if full_binder.exists():
                size_mb = full_binder.stat().st_size / (1024 * 1024)
                console.print(f"  [cyan]📚[/cyan] Full binder: [bold]{full_binder.name}[/bold]")
                console.print(f"     Size: [bold]{size_mb:.2f} MB[/bold]")
                console.print()
                return full_binder
        
        return None
    except Exception as e:
        console.print(f"  [red]❌[/red] Error: {e}")
        import traceback
        console.print(f"     [dim]{traceback.format_exc()}[/dim]")
        return None


def demonstrate_meta_cognitive_integration(demo_dir: Path):
    """Show how these tools integrate with WAFT's meta-cognitive layer."""
    console.print("\n[bold cyan]🧠 DEMONSTRATION 3: META-COGNITIVE INTEGRATION[/bold cyan]\n")
    
    console.print("These advanced tools work seamlessly with WAFT's")
    console.print("meta-cognitive memory system (_pyrite).\n")
    
    # Create integration explanation
    integration_file = demo_dir / "advanced_tools_integration.md"
    
    content = f"""# WAFT Advanced Tools Integration

Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Overview

This document explains how WAFT's advanced tools integrate with its meta-cognitive layer.

## Tools Demonstrated

### 1. Framework Self-Documentation

**Location:** `tools/framework_documentation/generate_framework_docs.py`

**What it does:**
- Recursively scans WAFT's codebase
- Extracts information about modules, classes, functions
- Generates comprehensive documentation
- **NO HARDCODED CONTENT** - everything is discovered through analysis

**Meta-Cognitive Integration:**
- Documents WAFT's own architecture
- Creates a feedback loop: documentation → development → documentation
- Enables recursive self-improvement

### 2. PDF Binder Organization

**Location:** `tools/pdf_binder_organizer/organize_pdfs.py`

**What it does:**
- Recursively scans any directory for PDFs
- Extracts metadata (title, author, pages, dates)
- Organizes into booklets (max 25 pages each)
- Creates full binder with all PDFs
- Saves comprehensive metadata to JSON

**Meta-Cognitive Integration:**
- Can organize WAFT's own documentation
- Creates structured knowledge collections
- Enables knowledge persistence and organization

## The Recursive Loop

1. **WAFT generates documents** → Creates PDFs
2. **WAFT organizes documents** → Creates binders
3. **WAFT documents itself** → Creates framework docs
4. **WAFT tracks its work** → Uses _pyrite
5. **WAFT improves** → Based on observations
6. **Cycle repeats** → Continuous enhancement

## Key Insight

These tools demonstrate WAFT's ability to:
- **Observe itself** (framework documentation)
- **Organize knowledge** (PDF binder)
- **Track its work** (_pyrite system)
- **Improve recursively** (feedback loops)

This is **recursive self-improvement through documentation and organization**.
"""
    
    integration_file.write_text(content)
    
    console.print("  [cyan]📝[/cyan] Created integration explanation")
    console.print(f"     File: [bold]{integration_file.name}[/bold]")
    console.print()
    console.print("  [cyan]💡[/cyan] These tools create a recursive improvement loop:")
    console.print("     WAFT documents → Organizes → Tracks → Improves → Documents...")
    console.print()


def create_advanced_demo_booklet(demo_dir: Path, framework_doc: Optional[Path], 
                                 pdf_binder: Optional[Path]) -> Path:
    """Create a comprehensive booklet documenting the advanced demo."""
    console.print("\n[bold cyan]📖 GENERATING ADVANCED DEMO BOOKLET[/bold cyan]\n")
    
    from jinja2 import Template
    from weasyprint import HTML
    
    booklet_template = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WAFT Advanced Demonstration</title>
    <style>
        @page {
            size: letter;
            margin: 0.75in;
            
            @top-center {
                content: "WAFT Advanced Demonstration";
                font-family: 'Times New Roman', serif;
                font-size: 9pt;
                color: #666;
            }
            
            @bottom-center {
                content: "Page " counter(page);
                font-family: 'Times New Roman', serif;
                font-size: 9pt;
                color: #666;
            }
        }
        
        @page :first {
            @top-center { content: none; }
        }
        
        body {
            font-family: 'Times New Roman', serif;
            font-size: 11pt;
            line-height: 1.6;
            color: #000;
        }
        
        .cover {
            text-align: center;
            padding-top: 2in;
        }
        
        .cover h1 {
            font-size: 32pt;
            font-weight: bold;
            margin-bottom: 0.3in;
            letter-spacing: 3px;
        }
        
        .cover .subtitle {
            font-size: 18pt;
            color: #333;
            margin-bottom: 0.5in;
        }
        
        h1 {
            font-size: 20pt;
            font-weight: bold;
            margin-top: 0.5in;
            margin-bottom: 0.3in;
            border-bottom: 3px solid #000;
            padding-bottom: 0.1in;
        }
        
        h2 {
            font-size: 16pt;
            font-weight: bold;
            margin-top: 0.4in;
            margin-bottom: 0.2in;
            color: #2c3e50;
        }
        
        .highlight-box {
            background: #f8f9fa;
            border-left: 4px solid #3498db;
            padding: 0.2in;
            margin: 0.2in 0;
        }
        
        .tool-card {
            background: #ffffff;
            border: 1px solid #ddd;
            padding: 0.2in;
            margin: 0.2in 0;
            border-radius: 4px;
        }
        
        .tool-title {
            font-weight: bold;
            font-size: 13pt;
            color: #2c3e50;
            margin-bottom: 0.1in;
        }
        
        code {
            font-family: 'Courier New', monospace;
            font-size: 10pt;
            background: #f0f0f0;
            padding: 0.05in;
            border-radius: 3px;
        }
    </style>
</head>
<body>
    <div class="cover">
        <h1>WAFT</h1>
        <div class="subtitle">Advanced Demonstration</div>
        <div class="subtitle" style="font-size: 14pt; margin-top: 0.3in;">
            World Architecture Framework & Templates
        </div>
        <div style="font-size: 12pt; color: #666; margin-top: 1.5in;">
            {{ date }}
        </div>
    </div>
    
    <h1>Introduction</h1>
    <p>
        This booklet documents WAFT's advanced capabilities, including self-documentation
        and intelligent PDF organization. These tools demonstrate WAFT's recursive
        self-improvement through documentation.
    </p>
    
    <h1>Demonstration 1: Framework Self-Documentation</h1>
    
    <div class="tool-card">
        <div class="tool-title">Framework Documentation Generator</div>
        <p>
            WAFT can inspect its own codebase and generate comprehensive documentation
            about how it functions. This is <strong>recursive self-documentation</strong> -
            the system describing itself.
        </p>
        <p><strong>Key Features:</strong></p>
        <ul>
            <li>Recursively scans WAFT's codebase</li>
            <li>Extracts information about modules, classes, functions</li>
            <li>Generates documentation based on actual findings</li>
            <li><strong>NO HARDCODED CONTENT</strong> - everything is discovered</li>
        </ul>
        {% if framework_doc %}
        <p><strong>Generated:</strong> Framework documentation PDF created</p>
        {% endif %}
    </div>
    
    <h1>Demonstration 2: PDF Binder Organization</h1>
    
    <div class="tool-card">
        <div class="tool-title">PDF Binder Organizer</div>
        <p>
            WAFT can recursively scan any directory, find all PDFs, extract metadata,
            and organize them into intelligent booklets (max 25 pages each).
        </p>
        <p><strong>Key Features:</strong></p>
        <ul>
            <li>Recursive directory scanning</li>
            <li>Metadata extraction (title, author, pages, dates)</li>
            <li>Smart booklet assembly (max 25 pages each)</li>
            <li>Full binder creation with all PDFs</li>
            <li>Comprehensive JSON metadata</li>
        </ul>
        {% if pdf_binder %}
        <p><strong>Generated:</strong> PDF binder with organized booklets</p>
        {% endif %}
    </div>
    
    <h1>Demonstration 3: Meta-Cognitive Integration</h1>
    
    <div class="highlight-box">
        <h2>The Recursive Loop</h2>
        <ol>
            <li><strong>WAFT generates documents</strong> → Creates PDFs</li>
            <li><strong>WAFT organizes documents</strong> → Creates binders</li>
            <li><strong>WAFT documents itself</strong> → Creates framework docs</li>
            <li><strong>WAFT tracks its work</strong> → Uses _pyrite system</li>
            <li><strong>WAFT improves</strong> → Based on observations</li>
            <li><strong>Cycle repeats</strong> → Continuous enhancement</li>
        </ol>
    </div>
    
    <h2>Key Insight</h2>
    <p>
        These tools demonstrate WAFT's ability to:
    </p>
    <ul>
        <li><strong>Observe itself</strong> (framework documentation)</li>
        <li><strong>Organize knowledge</strong> (PDF binder)</li>
        <li><strong>Track its work</strong> (_pyrite system)</li>
        <li><strong>Improve recursively</strong> (feedback loops)</li>
    </ul>
    
    <h1>Conclusion</h1>
    <p>
        This advanced demonstration showcases WAFT's recursive self-improvement
        capabilities. The system can observe itself, organize its knowledge, and
        continuously improve through documentation and feedback loops.
    </p>
    
    <div class="highlight-box">
        <p style="text-align: center; font-style: italic; margin-top: 0.5in;">
            <strong>WAFT documenting WAFT using WAFT.</strong><br>
            Recursive self-improvement through documentation.
        </p>
    </div>
</body>
</html>
"""
    
    template = Template(booklet_template)
    html_content = template.render(
        date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        framework_doc=framework_doc is not None,
        pdf_binder=pdf_binder is not None
    )
    
    booklet_path = demo_dir / "WAFT_Advanced_Demo_Booklet.pdf"
    
    with console.status("[bold cyan]Creating PDF booklet...[/bold cyan]"):
        HTML(string=html_content).write_pdf(str(booklet_path))
    
    size_mb = booklet_path.stat().st_size / (1024 * 1024)
    console.print(f"  [green]✅[/green] Advanced demo booklet generated")
    console.print(f"     File: [bold]{booklet_path.name}[/bold]")
    console.print(f"     Size: [bold]{size_mb:.2f} MB[/bold]")
    console.print()
    
    return booklet_path


def closing_summary(demo_dir: Path):
    """Display closing summary."""
    console.print("\n" + "=" * 80)
    console.print(Panel.fit(
        "[bold green]🎉 ADVANCED DEMONSTRATION COMPLETE![/bold green]\n\n"
        "What you witnessed:\n\n"
        "✅ Framework Self-Documentation\n"
        "   WAFT inspecting itself and generating documentation\n\n"
        "✅ PDF Binder Organization\n"
        "   Intelligent scanning and booklet assembly\n\n"
        "✅ Meta-Cognitive Integration\n"
        "   Tools working with WAFT's epistemic memory\n\n"
        "✅ Recursive Self-Improvement\n"
        "   Documentation → Organization → Tracking → Improvement",
        title="Summary",
        border_style="green"
    ))
    console.print("=" * 80)
    console.print()
    console.print(f"[bold]Demo folder:[/bold] [cyan]{demo_dir}[/cyan]")
    console.print()


# ============================================================================
# Main Demo Flow
# ============================================================================

def main():
    """Run the advanced demonstration."""
    try:
        # Setup
        project_root = Path(__file__).parent.parent.parent
        demo_dir = project_root / "advanced_demo_output"
        demo_dir.mkdir(exist_ok=True)
        
        # 1. Welcome
        welcome_message()
        
        # 2. Framework documentation
        framework_doc = demonstrate_framework_documentation(demo_dir)
        
        # 3. PDF organization
        pdf_binder = demonstrate_pdf_organization(demo_dir)
        
        # 4. Meta-cognitive integration
        demonstrate_meta_cognitive_integration(demo_dir)
        
        # 5. Generate booklet
        booklet = create_advanced_demo_booklet(demo_dir, framework_doc, pdf_binder)
        
        # 6. Closing
        closing_summary(demo_dir)
        
        # 7. Open booklet
        console.print("  [cyan]📖[/cyan] Opening advanced demo booklet...")
        if open_file(booklet):
            console.print("     [green]✅[/green] Booklet opened")
        console.print()
        
    except KeyboardInterrupt:
        console.print("\n\n[bold yellow]Demonstration interrupted by user.[/bold yellow]\n")
        sys.exit(0)
    except Exception as e:
        console.print(f"\n\n[bold red]❌ Error during demonstration:[/bold red] {e}")
        import traceback
        console.print(f"[dim]{traceback.format_exc()}[/dim]")
        sys.exit(1)


if __name__ == "__main__":
    main()
