#!/usr/bin/env python3
"""
Evolve Book Template
===================

Create a new template variant for D&D books using existing tools.
Adds field guide style option to the book generation system.

Usage:
    python scripts/evolve_book_template.py --template field-guide
    python scripts/evolve_book_template.py --template academic
    python scripts/evolve_book_template.py --list
"""

import argparse
import sys
from pathlib import Path
from typing import Any

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from rich.console import Console
from rich.table import Table

from src.waft.templates.dnd5e_latex import escape_latex, generate_storybook_latex

console = Console()


def generate_field_guide_storybook_latex(
    title: str,
    chapters: list[dict[str, Any]],
    author: str | None = None,
    output_path: Path | None = None,
    template_path: Path | None = None,
) -> Path:
    """
    Generate D&D storybook in field guide style - practical, rugged aesthetic.

    Uses standard book class with custom styling for field manual look.
    """
    if output_path is None:
        safe_name = title.replace(" ", "_").replace("'", "").lower()
        output_path = Path.cwd() / f"{safe_name}_field_guide.pdf"

    if template_path is None:
        project_root = Path(__file__).parent.parent
        template_path = project_root / "lib" / "dnd"

    if author is None:
        author = "WAFT Storyteller"

    # Build field guide style LaTeX
    latex_content = _build_field_guide_latex(title, chapters, author)

    # Compile LaTeX
    from src.waft.templates.dnd5e_latex import _compile_latex

    return _compile_latex(latex_content, output_path, template_path)


def _build_field_guide_latex(title: str, chapters: list[dict[str, Any]], author: str) -> str:
    """Build LaTeX content for field guide style storybook."""

    latex = f"""% D&D Field Guide Style Storybook
% Generated by WAFT Storyteller
% Title: {escape_latex(title)}

\\documentclass[11pt,letterpaper,twoside,openany]{{book}}

\\usepackage[utf8]{{inputenc}}
\\usepackage[T1]{{fontenc}}
\\usepackage{{geometry}}
\\usepackage{{fancyhdr}}
\\usepackage{{titlesec}}
\\usepackage{{xcolor}}
\\usepackage{{tcolorbox}}
\\usepackage{{booktabs}}
\\usepackage{{enumitem}}
\\usepackage{{multicol}}

% Field guide geometry - wider margins for notes
\\geometry{{
    left=0.75in,
    right=0.75in,
    top=0.75in,
    bottom=0.75in,
    headheight=0.3in,
    footskip=0.4in
}}

% Field guide colors
\\definecolor{{fgblack}}{{RGB}}{{0,0,0}}
\\definecolor{{fgyellow}}{{RGB}}{{255,255,0}}
\\definecolor{{fgred}}{{RGB}}{{204,0,0}}
\\definecolor{{fgblue}}{{RGB}}{{0,102,204}}
\\definecolor{{fgorange}}{{RGB}}{{255,153,0}}

% Page style - field guide headers
\\pagestyle{{fancy}}
\\fancyhf{{}}
\\fancyhead[L]{{\\textsc{{\\textbf{{FIELD GUIDE}}}}}}
\\fancyhead[R]{{\\textsc{{Page \\thepage}}}}
\\fancyfoot[C]{{\\textsc{{\\textbf{{FOR OPERATIONAL USE}}}}}}
\\renewcommand{{\\headrulewidth}}{{0.4pt}}
\\renewcommand{{\\footrulewidth}}{{0.4pt}}

% Title formatting - bold, uppercase, practical
\\titleformat{{\\chapter}}
    {{\\Huge\\bfseries\\color{{fgblack}}}}
    {{}}
    {{0em}}
    {{}}
    [\\titlerule[0.4pt]]

\\titleformat{{\\section}}
    {{\\Large\\bfseries\\color{{fgblack}}}}
    {{}}
    {{0em}}
    {{}}
    [\\titlerule[0.4pt]]

\\titleformat{{\\subsection}}
    {{\\large\\bfseries\\color{{fgblack}}}}
    {{}}
    {{0em}}
    {{}}

% Spacing
\\titlespacing*{{\\chapter}}{{0pt}}{{0.3in}}{{0.15in}}
\\titlespacing*{{\\section}}{{0pt}}{{0.2in}}{{0.1in}}
\\titlespacing*{{\\subsection}}{{0pt}}{{0.15in}}{{0.08in}}

% Field guide boxes
\\newtcolorbox{{readaloudbox}}{{
    colback=fgyellow!20,
    colframe=fgred,
    boxrule=3pt,
    arc=2pt,
    left=0.15in,
    right=0.15in,
    top=0.1in,
    bottom=0.1in,
    fonttitle={{\\bfseries\\textsc}}
}}

\\newtcolorbox{{notebox}}{{
    colback=fgblue!10,
    colframe=fgblue,
    boxrule=2pt,
    arc=2pt,
    left=0.15in,
    right=0.15in,
    top=0.1in,
    bottom=0.1in
}}

\\newtcolorbox{{warningbox}}{{
    colback=fgyellow!20,
    colframe=fgorange,
    boxrule=2pt,
    arc=2pt,
    left=0.15in,
    right=0.15in,
    top=0.1in,
    bottom=0.1in
}}

% Document metadata
\\title{{{escape_latex(title)}}}
\\author{{{escape_latex(author)}}}
\\date{{\\today}}

\\begin{{document}}

% Cover page - field guide style
\\begin{{titlepage}}
    \\centering
    \\vspace*{{0.5in}}
    
    % Series header
    {{\\Large\\bfseries\\textsc{{FIELD GUIDE}}}}
    
    \\vspace{{0.3in}}
    
    % Title box
    \\begin{{tcolorbox}}[
        colback=white,
        colframe=fgblack,
        boxrule=4pt,
        arc=0pt,
        width=0.9\\textwidth,
        left=0.2in,
        right=0.2in,
        top=0.3in,
        bottom=0.3in
    ]
    \\centering
    {{\\Huge\\bfseries {escape_latex(title)}}}
    \\end{{tcolorbox}}
    
    \\vfill
    
    % Classification box
    \\begin{{tcolorbox}}[
        colback=fgyellow,
        colframe=fgred,
        boxrule=2pt,
        width=0.7\\textwidth
    ]
    \\centering
    {{\\Large\\bfseries FOR OPERATIONAL USE}}
    \\end{{tcolorbox}}
    
    \\vspace{{0.3in}}
    
    \\textbf{{Author:}} {escape_latex(author)}\\\\
    \\textbf{{Date:}} \\today
    
    \\vspace{{0.5in}}
\\end{{titlepage}}

\\newpage
\\setcounter{{page}}{{1}}

\\tableofcontents

\\newpage

"""

    # Add chapters
    for i, chapter in enumerate(chapters, 1):
        chapter_title = chapter.get("title", f"Chapter {i}")
        chapter_content = chapter.get("content", "")
        read_aloud = chapter.get("read_aloud", [])
        sidebar = chapter.get("sidebar")
        monsters = chapter.get("monsters", [])

        latex += f"""
\\chapter{{{escape_latex(chapter_title)}}}

"""

        # Add read-aloud text in field guide style
        if read_aloud:
            for text in read_aloud:
                latex += f"""
\\begin{{readaloudbox}}
\\textbf{{READ ALOUD:}}\\\\
{escape_latex(text)}
\\end{{readaloudbox}}

"""

        # Add sidebar as note box
        if sidebar:
            sidebar_title = sidebar.get("title", "Note")
            sidebar_content = sidebar.get("content", "")
            latex += f"""
\\begin{{notebox}}
\\textbf{{{escape_latex(sidebar_title)}}}\\\\
{escape_latex(sidebar_content)}
\\end{{notebox}}

"""

        # Add main content (simplified - would use full markdown parser in production)
        from src.waft.templates.dnd5e_latex import _format_chapter_content

        latex += _format_chapter_content(chapter_content)

        # Add monster stat blocks (simplified)
        if monsters:
            for monster in monsters:
                monster_name = monster.get("name", "Monster")
                latex += f"""
\\begin{{warningbox}}
\\textbf{{{escape_latex(monster_name)}}}\\\\
\\textit{{Monster stat block would appear here}}
\\end{{warningbox}}

"""

        latex += "\n"

    latex += """\\end{document}
"""

    return latex


def generate_academic_storybook_latex(
    title: str,
    chapters: list[dict[str, Any]],
    author: str | None = None,
    output_path: Path | None = None,
    template_path: Path | None = None,
) -> Path:
    """
    Generate D&D storybook in academic paper style - two-column, scholarly aesthetic.
    """
    if output_path is None:
        safe_name = title.replace(" ", "_").replace("'", "").lower()
        output_path = Path.cwd() / f"{safe_name}_academic.pdf"

    if template_path is None:
        project_root = Path(__file__).parent.parent
        template_path = project_root / "lib" / "dnd"

    if author is None:
        author = "WAFT Storyteller"

    # Build academic style LaTeX
    latex_content = _build_academic_latex(title, chapters, author)

    # Compile LaTeX
    from src.waft.templates.dnd5e_latex import _compile_latex

    return _compile_latex(latex_content, output_path, template_path)


def _build_academic_latex(title: str, chapters: list[dict[str, Any]], author: str) -> str:
    """Build LaTeX content for academic paper style storybook."""

    latex = f"""% D&D Academic Paper Style Storybook
% Generated by WAFT Storyteller
% Title: {escape_latex(title)}

\\documentclass[11pt,letterpaper,twocolumn]{{article}}

\\usepackage[utf8]{{inputenc}}
\\usepackage[T1]{{fontenc}}
\\usepackage{{geometry}}
\\usepackage{{fancyhdr}}
\\usepackage{{titlesec}}
\\usepackage{{xcolor}}
\\usepackage{{abstract}}
\\usepackage{{booktabs}}

% Academic paper geometry
\\geometry{{
    left=0.75in,
    right=0.75in,
    top=0.75in,
    bottom=0.75in
}}

% Academic colors
\\definecolor{{acblack}}{{RGB}}{{0,0,0}}
\\definecolor{{acblue}}{{RGB}}{{0,51,102}}

% Page style
\\pagestyle{{fancy}}
\\fancyhf{{}}
\\fancyhead[C]{{\\textsc{{{escape_latex(title)}}}}}
\\fancyfoot[C]{{\\thepage}}
\\renewcommand{{\\headrulewidth}}{{0.4pt}}

% Title formatting
\\titleformat{{\\section}}
    {{\\large\\bfseries\\color{{acblack}}}}
    {{}}
    {{0em}}
    {{}}
    [\\titlerule[0.4pt]]

% Document metadata
\\title{{{escape_latex(title)}}}
\\author{{{escape_latex(author)}}}
\\date{{\\today}}

\\begin{{document}}

\\twocolumn[
\\maketitle
\\begin{{abstract}}
This document presents a comprehensive narrative in academic paper format, 
combining scholarly presentation with adventure storytelling.
\\end{{abstract}}
]

"""

    # Add chapters as sections
    for i, chapter in enumerate(chapters, 1):
        chapter_title = chapter.get("title", f"Section {i}")
        chapter_content = chapter.get("content", "")

        latex += f"""
\\section{{{escape_latex(chapter_title)}}}

"""

        # Add content (simplified)
        from src.waft.templates.dnd5e_latex import _format_chapter_content

        latex += _format_chapter_content(chapter_content)

        latex += "\n"

    latex += """\\end{document}
"""

    return latex


def list_templates():
    """List available book template styles."""
    templates = [
        ("dnd", "D&D 5e Official Style (default)"),
        ("field-guide", "Field Guide Style (practical, rugged)"),
        ("academic", "Academic Paper Style (two-column, scholarly)"),
    ]

    table = Table(title="Available Book Templates")
    table.add_column("Template", style="cyan")
    table.add_column("Description", style="green")

    for name, desc in templates:
        table.add_row(name, desc)

    console.print(table)


def main():
    parser = argparse.ArgumentParser(
        description="Evolve book template - create new template variants"
    )
    parser.add_argument(
        "--template", choices=["dnd", "field-guide", "academic"], help="Template style to use"
    )
    parser.add_argument("--list", action="store_true", help="List available templates")
    parser.add_argument("--title", help="Book title")
    parser.add_argument("--file", type=Path, help="Input file with chapters")
    parser.add_argument("--demo", action="store_true", help="Use demo content")

    args = parser.parse_args()

    if args.list:
        list_templates()
        return

    if not args.template:
        console.print("[red]Error: --template required (use --list to see options)[/red]")
        return

    # Get book content
    if args.demo:
        from scripts.create_book import create_sample_chapters

        chapters = create_sample_chapters()
        title = "Demo Adventure Book"
    elif args.file:
        from scripts.create_book import parse_chapters_from_file

        chapters = parse_chapters_from_file(args.file)
        title = args.title or args.file.stem
    elif args.title:
        console.print("[red]Error: Need --file or --demo for content[/red]")
        return
    else:
        console.print("[red]Error: Need --title with --file or --demo[/red]")
        return

    if not title:
        title = "Untitled Book"

    console.print(f"[green]Generating book with {args.template} template...[/green]")

    # Generate based on template
    try:
        if args.template == "field-guide":
            output_path = generate_field_guide_storybook_latex(
                title=title, chapters=chapters, author="WAFT Storyteller"
            )
        elif args.template == "academic":
            output_path = generate_academic_storybook_latex(
                title=title, chapters=chapters, author="WAFT Storyteller"
            )
        else:  # dnd
            output_path = generate_storybook_latex(
                title=title, chapters=chapters, author="WAFT Storyteller"
            )

        console.print(f"[green]✅ Book generated: {output_path}[/green]")

        # Try to open
        import platform
        import subprocess

        if platform.system() == "Darwin":
            subprocess.run(["open", str(output_path)])

    except Exception as e:
        console.print(f"[red]❌ Error: {e}[/red]")
        import traceback

        traceback.print_exc()


if __name__ == "__main__":
    main()
