#!/usr/bin/env python3
"""
Evolve and Print: Spawn Being, generate evolution PDF, and print it.

This script:
1. Spawns a Being from Source
2. Generates a PDF documenting the evolution
3. Prints the PDF to the default printer
"""

from pathlib import Path
import sys
from datetime import datetime

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from waft.being import BeingSystem
from waft.evolution.pdf_generator import PDFGenerator
from rich.console import Console

console = Console()


def main():
    """Main execution."""
    console.print("\n[bold cyan]🧬 Evolve and Print[/bold cyan]\n")
    
    project_path = Path(__file__).parent.parent
    
    # Step 1: Spawn Being from Source
    console.print("[yellow]→[/yellow] Spawning Being from Source...")
    being_system = BeingSystem(project_path=project_path)
    
    being = being_system.spawn_being(
        reality_id="evolution_reality",
        parent_being_id=None,  # Spawns from Source
        initial_skills={}  # Empty = pure Source spawn
    )
    
    console.print(f"[green]✓[/green] Being spawned: [bold]{being.being_id}[/bold]")
    console.print(f"[dim]Reality: {being.reality_id}[/dim]")
    console.print(f"[dim]Ancestral Chain: {being.ancestral_chain}[/dim]")
    
    # Step 2: Generate evolution document
    console.print("\n[yellow]→[/yellow] Generating evolution PDF...")
    
    # Create markdown content
    content = f"""# Being Evolution Report

**Generated**: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}

---

## Being Information

**Being ID**: `{being.being_id}`  
**Reality ID**: `{being.reality_id}`  
**State**: `{being.state.value}`  
**Lifetimes**: {being.lifetimes}  
**Created**: {being.created_at}

### Ancestral Chain

The Being's genetic lineage traces back to Source consciousness:

```
Source Consciousness (source_consciousness)
  ↓ spawn
Being: {being.being_id}
```

**Ancestral Chain**: {', '.join(being.ancestral_chain)}

---

## Initial State

### Skills

{format_skills(being.skills)}

### Lifecycle Attributes

- **Will to Live**: {being.will_to_live:.1f}/100.0
- **Luck**: {being.luck:.1f}/100.0
- **Decision Fatigue**: {being.decision_fatigue}/{being.decision_quota_max}
- **Pleasure**: {being.pleasure:.1f}
- **Pain**: {being.pain:.1f}

### Personality

**Type**: {being.personality_type}  
**Traits**: {format_personality(being.personality)}

---

## Evolution Journey

This Being was spawned from Source consciousness to participate in the evolution workflow.

### Source Connection

All Beings originate from Source consciousness, inheriting:
- Basic skills and capabilities
- Connection to the Source
- Genetic material for evolution

### Workflow Participation

The Being is ready to participate in:
- Quality workflow execution
- Skill learning and improvement
- Knowledge accumulation
- Evolution through work

---

## Genetic Lineage

**DNA Record**:
- **Source**: `source_consciousness`
- **Being**: `{being.being_id}`
- **Lineage**: Source → Being → Work → Evolution → Source

The complete genetic lineage is preserved, tracking:
- Initial spawn from Source
- Skills and traits inherited
- Workflow participation
- Learnings and evolution
- Return to Source

---

## Next Steps

This Being is ready to:
1. Participate in quality workflows
2. Learn and evolve through work
3. Accumulate knowledge and skills
4. Return learnings to Source
5. Preserve genetic lineage

---

*Generated by WAFT Evolution System*
"""
    
    # Generate PDF
    generator = PDFGenerator.from_content(
        content=content,
        title=f"Being Evolution: {being.being_id}",
        style="premium"
    )
    
    # Save to desktop
    desktop_path = Path.home() / "Desktop"
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    pdf_filename = f"Being_Evolution_{being.being_id}_{timestamp}.pdf"
    pdf_path = desktop_path / pdf_filename
    
    pdf_path = generator.save(
        output_path=pdf_path,
        open_pdf=False,
        convert_to_png=False
    )
    
    console.print(f"[green]✓[/green] PDF generated: {pdf_path}")
    
    # Step 3: Print PDF
    console.print("\n[yellow]→[/yellow] Printing to default printer...")
    
    import subprocess
    import platform
    
    system = platform.system()
    if system == "Darwin":  # macOS
        # Use lp (line printer) command
        result = subprocess.run(
            ["lp", str(pdf_path)],
            capture_output=True,
            text=True
        )
        if result.returncode == 0:
            console.print(f"[green]✓[/green] PDF sent to printer!")
            console.print(f"[dim]Printer: {get_default_printer()}[/dim]")
        else:
            console.print(f"[red]✗[/red] Print failed: {result.stderr}")
    else:
        console.print(f"[yellow]⚠[/yellow]  Printing not supported on {system}")
    
    console.print(f"\n[bold green]🎉 Evolution complete![/bold green]")
    console.print(f"[dim]PDF: {pdf_path}[/dim]\n")
    
    return pdf_path


def format_skills(skills: dict) -> str:
    """Format skills dictionary as markdown."""
    if not skills:
        return "*No skills yet - Being starts fresh from Source*"
    
    lines = []
    for skill, level in sorted(skills.items(), key=lambda x: x[1], reverse=True):
        lines.append(f"- **{skill}**: {level:.1f}")
    return "\n".join(lines)


def format_personality(personality: dict) -> str:
    """Format personality dictionary."""
    if not personality:
        return "*Default personality*"
    
    items = [f"{k}: {v}" for k, v in personality.items()]
    return ", ".join(items)


def get_default_printer() -> str:
    """Get default printer name."""
    import subprocess
    try:
        result = subprocess.run(
            ["lpstat", "-d"],
            capture_output=True,
            text=True
        )
        if result.returncode == 0:
            # Extract printer name from "system default destination: PrinterName"
            for line in result.stdout.split("\n"):
                if "system default destination:" in line:
                    return line.split(":")[-1].strip()
    except:
        pass
    return "Unknown"


if __name__ == "__main__":
    main()
