// sitrep_template.typ - Military-style SITREP Template
// Part of DIALECTIC Engine Tools
//
// Usage:
//   #import "sitrep_template.typ": sitrep-doc, sitrep-section

// SITREP Document Template
#let sitrep-doc(
  dtg: datetime.today().display("[day][hour][minute]Z [month repr:short] [year]").to-upper(),
  classification: "UNCLASSIFIED",
  unit: "DIALECTIC ENGINE",
  body
) = {
  set page(
    paper: "us-letter",
    margin: (x: 1in, y: 0.75in),
    header: [
      #set text(8pt, weight: "bold")
      #classification
      #h(1fr)
      #unit
    ],
    footer: [
      #set text(8pt)
      #classification
      #h(1fr)
      #context counter(page).display("Page 1 of 1", both: true)
    ],
  )
  
  set text(font: "New Computer Modern", size: 11pt)
  
  // Header Block
  align(center)[
    #text(16pt, weight: "bold")[SITUATION REPORT (SITREP)]
    #v(0.5em)
    #table(
      columns: (1fr, 1fr),
      stroke: none,
      [*DTG:* #dtg], [*CLASSIFICATION:* #classification],
    )
  ]
  
  line(length: 100%, stroke: 1pt)
  v(1em)
  
  body
  
  // Footer
  v(2em)
  line(length: 100%, stroke: 0.5pt)
  align(center)[
    #text(8pt, fill: gray)[
      Generated by DIALECTIC Engine // Port 2112 \\
      Hegelian Dialectics: Thesis, Antithesis, Synthesis
    ]
  ]
}

// SITREP Section (numbered 1-5 per military format)
#let sitrep-section(number, title, body) = {
  v(0.5em)
  text(12pt, weight: "bold")[#number. #upper(title)]
  v(0.3em)
  pad(left: 1em)[#body]
  v(0.5em)
}

// Subsection (a, b, c format)
#let sitrep-subsection(letter, title, body) = {
  pad(left: 1em)[
    text(11pt, weight: "bold")[#letter. #title]
    #v(0.2em)
    #pad(left: 1em)[#body]
  ]
}

// Status indicator
#let status-indicator(status) = {
  let (color, icon) = if status == "complete" {
    (rgb("#3fb950"), "●")
  } else if status == "in-progress" {
    (rgb("#f0883e"), "◐")
  } else if status == "pending" {
    (rgb("#8b949e"), "○")
  } else {
    (rgb("#f85149"), "✗")
  }
  
  text(fill: color)[#icon #status]
}

// Priority marker
#let priority(level) = {
  let color = if level == "high" { rgb("#f85149") }
              else if level == "medium" { rgb("#f0883e") }
              else { rgb("#8b949e") }
  
  box(
    fill: color.lighten(80%),
    inset: (x: 6pt, y: 2pt),
    radius: 3pt,
  )[
    #text(8pt, weight: "bold", fill: color)[#upper(level)]
  ]
}

// Action item
#let action-item(description, priority: "medium", assignee: none) = {
  block(
    fill: luma(248),
    inset: 10pt,
    radius: 4pt,
    width: 100%,
  )[
    #priority(priority)
    #h(0.5em)
    #description
    #if assignee != none [
      #h(1fr)
      #text(8pt, fill: gray)[Assignee: #assignee]
    ]
  ]
}

// Timeline entry
#let timeline-entry(time, event, status: "complete") = {
  grid(
    columns: (auto, 1fr, auto),
    gutter: 1em,
    [#text(9pt, fill: gray)[#time]],
    [#event],
    [#status-indicator(status)],
  )
}

// Resource table
#let resource-table(resources) = {
  table(
    columns: (1fr, auto, auto),
    fill: (_, y) => if y == 0 { luma(230) } else { none },
    [*Resource*], [*Status*], [*Notes*],
    ..resources.map(r => (
      [#r.name],
      [#status-indicator(r.status)],
      [#r.notes],
    )).flatten(),
  )
}

// Classification banner
#let classification-banner(level) = {
  let color = if level == "CLASSIFIED" { rgb("#f85149") }
              else if level == "CONFIDENTIAL" { rgb("#f0883e") }
              else if level == "SENSITIVE" { rgb("#1f6feb") }
              else { rgb("#8b949e") }
  
  align(center)[
    #box(
      fill: color,
      inset: (x: 20pt, y: 5pt),
      radius: 0pt,
      width: 100%,
    )[
      #text(10pt, weight: "bold", fill: white)[#level]
    ]
  ]
}
