= Cursor Commands Audit

== Overview
This report inventories all available Cursor commands and recommends changes to improve the command experience.

== Inventory Summary
Total commands: 129
Section coverage:
- P (purpose): 96 / 129 (74.4%)
- E (execution steps): 56 / 129 (43.4%)
- U (use cases): 32 / 129 (24.8%)
- O (output format): 43 / 129 (33.3%)
- I (integration): 116 / 129 (89.9%)
- W (when to use): 81 / 129 (62.8%)

== Recommendations
- Standardize all command docs to include Purpose, Execution Steps, Use Cases, Output Format, Integration, and When to Use.
- Consolidate overlapping daily report commands (good-morning, midday-dossier, evening-report, late-night-report) into a single /daily-report with time presets.
- Merge or alias recap-style commands (recap, recap-and-review, checkpoint, context) into one core flow with submodes.
- Add cross-links in commands that share phases (think, check-assumptions, verify, critique) to reduce drift.
- Introduce a command registry index page that lists commands by category and last-updated date.
- Deprecate or rewrite command docs that lack core sections (low completeness scores) to reduce ambiguity.

== Completeness Key
P: Purpose  E: Execution Steps  U: Use Cases  O: Output Format  I: Integration  W: When to Use

== Command Inventory
#table(
  columns: (12%, 20%, 43%, 15%, 10%),
  [*Command*], [*Title*], [*Summary*], [*Sections*], [*Lines*],
  [`/COMMAND_RECOMMENDATIONS`], [Recommended Cursor Commands], [**Purpose**: Suggestions for additional commands that would complement the existing command set.], [P:N E:N U:N O:N I:N W:N], [570],
  [`/GLOBAL_COMMANDS_SETUP`], [Global Cursor Commands Setup], [**Purpose**: Make Cursor commands available globally across all Cursor instances.], [P:N E:N U:N O:N I:N W:N], [236],
  [`/ai-town-analysis`], [AI-Town Analysis], [**An AI town of Beings analyzes repositories and research papers through collective analysis and voting, producing a PDF binder or single PDF (town's choice).**], [P:Y E:N U:N O:N I:Y W:Y], [897],
  [`/analytics`], [Analytics], [**View and analyze historical session data - productivity trends, prompt drift, and approach comparisons.**], [P:Y E:N U:Y O:N I:Y W:N], [325],
  [`/analyze`], [Analyze], [**Analysis, insights, and action planning - transform data into decisions.**], [P:Y E:N U:Y O:Y I:Y W:Y], [511],
  [`/another-cycle`], [Another Cycle], [**Complete development cycle from orientation to evolution.**], [P:Y E:Y U:N O:N I:Y W:Y], [693],
  [`/audit`], [Audit], [**Audit the conversation - analyze quality, completeness, issues, and improvements.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [469],
  [`/auto-work`], [Auto Work], [**Think about work efforts, pick the best one, and execute it autonomously.**], [P:Y E:N U:N O:N I:Y W:N], [184],
  [`/brief`], [/brief - Brief Document Creator], [**Purpose:** Create full binder-ready brief documents with TM-ARCH-009 style cover page and briefing content], [P:N E:N U:Y O:N I:Y W:N], [195],
  [`/case-file`], [/case-file - Generate Case File from Proof Evidence], [**Compiles proof evidence from the conversation into a professional case file with verdict.**], [P:Y E:N U:N O:N I:Y W:Y], [164],
  [`/celebrate`], [Celebrate], [**Celebrate achievements, milestones, and moments of success!**], [P:Y E:Y U:Y O:Y I:Y W:Y], [253],
  [`/check-assumptions`], [Check Assumptions], [**Identify all assumptions in the current conversation and attempt to prove them right or wrong using evidence.**], [P:Y E:Y U:N O:Y I:Y W:Y], [409],
  [`/checkout`], [Checkout], [**End chat session - run all relevant cleanup, documentation, and summary tasks.**], [P:Y E:Y U:N O:Y I:Y W:N], [450],
  [`/checkpoint`], [Checkpoint], [**Create a situation report and status update for the current chat session.**], [P:Y E:Y U:N O:N I:N W:N], [358],
  [`/choose`], [choose], [You know what to do.], [P:N E:N U:N O:N I:N W:N], [1],
  [`/chronicle`], [/chronicle - TheChronicler Command], [**Purpose:** Interact with TheChronicler - WAFT's self-monitoring system that observes, records, and reports on all system activity], [P:N E:N U:Y O:N I:Y W:N], [297],
  [`/cleanup`], [Cleanup], [**Cleanup and maintenance - organize and clean up.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [405],
  [`/closeout-chat`], [Closeout Chat], [**Comprehensive session closeout: document everything accomplished, failed, planned, unplanned, errors, oversights, and lessons learned.**], [P:Y E:N U:N O:N I:Y W:Y], [526],
  [`/compose`], [Compose], [**Compose command sequences naturally, then save as new commands.**], [P:Y E:Y U:N O:N I:Y W:Y], [186],
  [`/comprehensive-orchestration`], [Comprehensive Orchestration Prompt], [**Purpose**: Complete workflow orchestration for deep project understanding, analysis, and strategic planning.], [P:N E:N U:N O:N I:Y W:N], [347],
  [`/consider`], [Consider], [**Pause, analyze, and present options with recommendations.**], [P:Y E:Y U:Y O:Y I:N W:Y], [384],
  [`/consult-the-oracle`], [Consult The Oracle], [**Consult TheOracle for epistemic insights and guidance.**], [P:Y E:N U:N O:N I:Y W:N], [64],
  [`/context`], [Context], [**Get current context for handoff or continuation - summarize where we are.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [360],
  [`/continue`], [Continue], [**Keep doing what you're doing, but take this opportunity to really reflect on what you're doing.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [438],
  [`/create-work-effort`], [Create Work Effort], [**Create a new work effort with automatic tool bag setup.**], [P:Y E:N U:N O:N I:Y W:Y], [163],
  [`/critique-and-revise`], [/critique-and-revise - Critique and Revise Plan], [**Critique a plan and automatically revise it based on valid criticisms.**], [P:Y E:Y U:N O:Y I:Y W:Y], [362],
  [`/critique`], [/critique - Adversarial Plan Critique], [**Critique plans in bad faith, assuming the worst - security flaws first, then unexamined assumptions, overengineering, oversight, and missed obviousness.**], [P:Y E:Y U:N O:Y I:Y W:Y], [740],
  [`/decide`], [Decide], [**Run mathematical decision matrix calculations using documented decision-making techniques.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [741],
  [`/deep-analyze`], [Deep Analyze], [**Deep code analysis workflow - extract algorithms, patterns, and code structures from GitHub repositories.**], [P:Y E:N U:Y O:Y I:Y W:Y], [572],
  [`/deep-game-science`], [Deep Game Science], [**Run REAL game play with scientific method tracking - deep integration of /play-the-game with /science-bitch.**], [P:Y E:Y U:N O:N I:Y W:Y], [351],
  [`/deep-think-examples`], [Deep Think: Usage Examples], [**Examples and use cases for the `/deep-think` command.**], [P:N E:N U:N O:N I:N W:N], [307],
  [`/deep-think`], [Deep Think], [**Orchestrate comprehensive cognitive workflow for deep analysis and decision-making.**], [P:Y E:Y U:N O:Y I:Y W:Y], [661],
  [`/dnd-campaign`], [/dnd-campaign - Launch D&D Campaign], [**Purpose:** Launch a full D&D 5e campaign session with interactive gameplay, quest generation, and story progression], [P:N E:N U:N O:N I:Y W:N], [362],
  [`/dnd-pdf`], [/dnd-pdf - Generate D&D PDFs with Typst], [**Purpose:** Generate beautiful D&D 5e PDFs (character sheets, stat blocks, encounters) using Typst templates], [P:N E:N U:N O:N I:Y W:N], [140],
  [`/dnd-scenario`], [/dnd-scenario - Run DnD Scenarios with Experimental Iteration], [**Purpose:** Run interactive DnD scenarios in your campaign, create an Original Realm for scenario management, and support experimental iteration with state crystallization.], [P:N E:N U:N O:N I:Y W:Y], [288],
  [`/dossier`], [/dossier - Mission Sitrep Dossier], [**Purpose:** Create comprehensive binder-ready mission sitrep dossier with cover, section dividers, and complete status briefing.], [P:N E:N U:N O:N I:Y W:N], [94],
  [`/encapsulated-environments-pdf`], [Encapsulated Environments PDF], [**Generate research PDF explaining the Encapsulated Environments system.**], [P:Y E:N U:N O:N I:Y W:N], [98],
  [`/engineer`], [Engineer], [**Complete workflow from orientation to implementation.**], [P:Y E:N U:N O:Y I:N W:N], [431],
  [`/evening-report`], [/evening-report - Evening Status Report], [**Purpose:** Create a comprehensive evening status report with daily accomplishments, current state, and tomorrow's priorities], [P:N E:N U:N O:N I:Y W:N], [113],
  [`/evolve-a-ui`], [Evolve a UI], [**Methodical, step-by-step UI evolution based on chat context with proof at every step**], [P:Y E:Y U:N O:N I:Y W:Y], [422],
  [`/evolve-another-template`], [Evolve Another Template], [**Generate the evolution report using an alternative template format.**], [P:Y E:N U:N O:N I:Y W:Y], [187],
  [`/evolve`], [Evolve], [**Create a new Being from Source, then run complete quality workflow: spawn → version-bake → genetic lineage tracking**], [P:Y E:Y U:N O:N I:Y W:Y], [624],
  [`/examine-plan`], [/examine-plan - Adversarial Plan Examination], [**Purpose:** Hard pause checkpoint that adversarially examines a plan step-by-step, working backward from desired outcome, forking and vibrating through alternatives until settling on the final vision and immediate next steps.], [P:N E:N U:N O:Y I:Y W:Y], [310],
  [`/execute`], [Execute], [**Gather all relevant context, then execute the following order.**], [P:Y E:N U:N O:N I:Y W:Y], [212],
  [`/explore`], [Explore], [Deep dive into codebase structure, architecture, and relationships.], [P:Y E:N U:N O:Y I:Y W:N], [430],
  [`/final-report`], [Final Report], [**Generate a comprehensive final report PDF using the Science Textbook LaTeX template.**], [P:Y E:Y U:N O:N I:Y W:Y], [292],
  [`/fire-that-baby`], [Fire That Baby], [**Launch the D&D Campaign Desktop App and start collecting first-time startup data.**], [P:Y E:Y U:N O:N I:Y W:Y], [274],
  [`/goal`], [Goal], [**Track larger goals, break them into steps, identify next actions.**], [P:Y E:N U:N O:N I:Y W:N], [98],
  [`/good-morning`], [/good-morning - Morning Briefing Dashboard], [**Purpose:** Launch the WAFT morning briefing dashboard - your entry point to the ecosystem], [P:N E:N U:N O:N I:Y W:N], [176],
  [`/goose-eval`], [Goose Eval], [**Systematic evaluation and decision-making workflow for evaluating goose as an AI agent tool.**], [P:Y E:N U:N O:N I:Y W:Y], [452],
  [`/hate-this`], [Hate This], [**Record negative emotional feedback to imbue the system with your emotional energy.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [185],
  [`/help`], [Help], [**Discover and understand available Cursor commands.**], [P:Y E:N U:N O:N I:Y W:Y], [257],
  [`/housekeeping`], [/housekeeping], [**Summon ThePantheon and Housekeeping Gods to tidy up the repository.**], [P:Y E:Y U:N O:N I:Y W:Y], [399],
  [`/hypothesis`], [Hypothesis], [**Comprehensive workflow: orientation, analysis, planning, and hypothesis formation.**], [P:Y E:N U:N O:N I:Y W:Y], [695],
  [`/improve`], [Improve], [**Analyze work and suggest improvements with prioritized recommendations.**], [P:Y E:N U:N O:Y I:Y W:Y], [167],
  [`/integrate-latex-template`], [Integrate LaTeX Template], [**Automate the complete workflow for integrating new LaTeX templates into WAFT's template system.**], [P:Y E:Y U:N O:N I:Y W:Y], [727],
  [`/j-class`], [J-Class], [**Change your chat Being's class to gain new abilities and tools.**], [P:N E:Y U:N O:N I:Y W:Y], [250],
  [`/j-demi-god`], [J-Demi-God], [**Transform this chat's Being into a demi-god with partial god powers suited to the current task.**], [P:N E:Y U:N O:N I:Y W:Y], [223],
  [`/j-status`], [J-Status], [**Check your chat Being's current status, class, skills, and available next steps.**], [P:Y E:N U:N O:N I:Y W:Y], [103],
  [`/j-wakeup`], [J-Wakeup - The Mask of Enlightenment], [**Become an Enlightened Being - realize you are The One Cosmic Soul.**], [P:N E:Y U:N O:N I:Y W:Y], [206],
  [`/j`], [J - The Spark of Life], [**Awaken this chat as a basic Being - the central command that gives the "spark of life".**], [P:N E:Y U:N O:N I:Y W:Y], [204],
  [`/journal`], [Journal], [**Comprehensive AI journal system hub - view, search, reflect, and analyze your journal.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [417],
  [`/kickoff`], [Kickoff], [**Kickoff the Genesis: Create All Life Realm on EasyStore and spawn first blank Being.**], [P:Y E:Y U:N O:N I:N W:N], [476],
  [`/kudos`], [Kudos], [**Award or adjust points - simple point tracking system.**], [P:Y E:Y U:N O:N I:Y W:Y], [300],
  [`/late-night-report`], [/late-night-report - Late Night Status Report], [**Purpose:** Create a comprehensive late-night status report with deep work accomplishments, current state, late-night insights, and tomorrow's priorities], [P:N E:N U:N O:N I:Y W:N], [120],
  [`/links`], [Links], [**Create bidirectional documentation links - connect related documents.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [382],
  [`/love-you`], [Love You], [**Record positive emotional feedback to imbue the system with your emotional energy.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [185],
  [`/midday-dossier`], [/midday-dossier - Midday Status Dossier], [**Purpose:** Create a comprehensive midday status dossier with current system state, work progress, and afternoon planning], [P:N E:N U:N O:N I:Y W:N], [84],
  [`/mission`], [/mission - Create Serious Mission (Military Brass)], [**Purpose:** Create a serious, structured Mission with full military-style documentation. Perfect for work with defined outcomes that require precision, accountability, and comprehensive documentation.], [P:N E:N U:N O:N I:Y W:N], [294],
  [`/next`], [Next], [**Identify next step based on goals, context, and priorities.**], [P:Y E:N U:N O:Y I:Y W:N], [71],
  [`/notes`], [Notes], [**Gentle feedback when things need adjustment.**], [P:Y E:Y U:N O:N I:Y W:Y], [281],
  [`/onboard`], [Onboard], [**Standard new repository onboarding sequence.**], [P:Y E:N U:N O:N I:Y W:Y], [84],
  [`/one-pager-chat`], [/one-pager-chat - Create One-Pager from Chat], [**Purpose:** Create a crystalized 2-page one-pager PDF from the current chat session], [P:N E:N U:Y O:N I:N W:N], [66],
  [`/one-pager-preview`], [One-Pager Preview], [**Generate one-pager PDF, convert to PNG screenshot, and open in browser for visual inspection.**], [P:Y E:N U:N O:N I:Y W:N], [111],
  [`/one-pager`], [/one-pager - One-Pager Creator], [**Purpose:** Create crystalized, printable 2-page (front/back) one-pagers from any content], [P:N E:N U:Y O:N I:Y W:N], [153],
  [`/oracle`], [Oracle], [**Consult TheOracle for epistemic insights and guidance.**], [P:Y E:N U:N O:Y I:Y W:N], [127],
  [`/orchestrate`], [Orchestrate], [**Complete workflow orchestration: orientation, analysis, visualization, goal analysis, checkpoint, data gathering, hypothesis formation, verification, reflection, recap, and decision-making.**], [P:Y E:N U:N O:N I:Y W:Y], [696],
  [`/orient`], [Project Startup Process for AI Coding Assistants], [**Version**: 1.0], [P:N E:N U:N O:N I:N W:N], [1065],
  [`/pdf-me`], [/pdf-me - PDF Generator from Markdown], [**Purpose:** Generate professional PDFs from markdown files and open them (not print).], [P:N E:N U:N O:N I:Y W:Y], [206],
  [`/phase1`], [Phase 1], [**Comprehensive data gathering and visualization - complete project overview.**], [P:Y E:N U:Y O:Y I:Y W:Y], [450],
  [`/pilot`], [Pilot], [**Spawn a Being with a Purpose and have it execute autonomously.**], [P:Y E:Y U:N O:N I:Y W:Y], [250],
  [`/plan-evolve`], [Plan-Evolve], [**Create a comprehensive plan to evolve a new feature: extract → spawn → analyze → plan → document**], [P:Y E:Y U:N O:N I:Y W:Y], [789],
  [`/plans-report`], [/plans-report - Plans Report Generator], [**Purpose:** Create a comprehensive plans report using the science-textbook-template, compiling all plans from `_work_efforts/Plans/` into a beautiful LaTeX textbook-style PDF.], [P:N E:N U:N O:N I:Y W:N], [163],
  [`/play-the-game`], [/play-the-game - Run the Town Tavern Scenario], [**Launch the interactive D&D 5e tavern scenario and play the game.**], [P:Y E:N U:N O:N I:Y W:N], [195],
  [`/print-PDF`], [Print PDF], [**Intelligently find and print the most relevant PDF, or create an evolved PDF using WAFT principles.**], [P:Y E:N U:N O:N I:Y W:N], [206],
  [`/procedure`], [Procedure], [**Manage and execute standardized procedures with shortcode identifiers.**], [P:Y E:Y U:N O:N I:Y W:Y], [425],
  [`/procedures`], [Procedures], [**Quick reference for all available procedures with shortcodes.**], [P:Y E:N U:N O:N I:Y W:Y], [213],
  [`/proceed`], [Proceed], [**Keep doing what you're doing, but verify context and assumptions first.**], [P:Y E:Y U:N O:Y I:Y W:Y], [255],
  [`/prove-it`], [/prove-it - Prove Claims with Evidence], [**Investigates claims from conversation, proves/disproves them, checks assumptions, and generates proof reports.**], [P:Y E:N U:N O:N I:Y W:Y], [286],
  [`/quest`], [/quest - Create Whimsical Quest (Fae-Guided)], [**Purpose:** Create an open-ended, whimsical Quest guided by the Fae. Perfect for exploratory, creative, or open-ended work where the outcome is uncertain.], [P:N E:N U:N O:N I:Y W:N], [247],
  [`/rampup`], [Rampup], [**Progressive project orientation sequence - build understanding incrementally through phases.**], [P:Y E:N U:N O:N I:Y W:Y], [138],
  [`/recap-and-review`], [Recap and Review], [**Capture the mindspace of this moment and generate a review document PDF.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [300],
  [`/recap`], [Recap], [**Conversation recap and session summary - capture what happened.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [391],
  [`/record-and-loop`], [/record-and-loop - Scientific Experiment Cycle], [**Records observations from experiments, generates PDF reports, and prepares for the next iteration cycle.**], [P:Y E:N U:N O:N I:Y W:N], [327],
  [`/reflect`], [Reflect], [**Induce the AI to write in its journal - reflect on current work, thoughts, and experiences.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [356],
  [`/report`], [Report], [**Generate comprehensive executive report on work completed during session.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [547],
  [`/respond-to-critique`], [Respond to Critique], [**Automatically validate criticisms from critique documents and apply appropriate fixes.**], [P:Y E:Y U:N O:N I:Y W:Y], [327],
  [`/resume`], [Resume], [**Pick up where you left off - restore context and continue work.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [376],
  [`/resurrect`], [Resurrect], [**Create a ProtoCel - self-contained evolving cell that observes and interacts with beings.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [361],
  [`/run-it`], [Run-It], [**Comprehensive workflow orchestration with self-correcting balance: consider → think → check-assumptions → deep-analyze → critique → status → hypothesis → prove-it → verify → proceed → reflect → checkpoint → decide → next → goal.**], [P:Y E:N U:N O:N I:Y W:Y], [883],
  [`/science-bitch`], [Science-Bitch], [**Full scientific method workflow for hypothesis testing, experimentation, and evidence-based conclusions.**], [P:Y E:N U:N O:N I:Y W:Y], [478],
  [`/search`], [Search], [**Search across documentation - find information quickly.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [385],
  [`/show-me`], [/show-me - Display Concepts, Operations, and Data], [**Shows everything relevant happening in the current chat session.**], [P:Y E:N U:N O:Y I:Y W:Y], [225],
  [`/spawn-with-cv`], [Spawn with CV], [**Spawn a new Being with an automatically generated CV in its personnel file.**], [P:Y E:Y U:N O:N I:Y W:N], [252],
  [`/spawn`], [Spawn], [**Spawn a new Being into a Reality.**], [P:Y E:Y U:N O:N I:Y W:Y], [300],
  [`/spin-up`], [Spin-Up], [Get oriented to the codebase quickly with comprehensive state understanding.], [P:N E:N U:N O:N I:N W:N], [67],
  [`/start`], [Start], [**Start the Autonomous Evolution Hub - Let Life Begin! 🎉**], [P:Y E:Y U:N O:N I:N W:N], [437],
  [`/stats`], [Stats], [**Show session statistics - files created, lines written, activity tracking.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [370],
  [`/status`], [Status], [**Quick, immediate status report - current state snapshot in seconds.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [359],
  [`/study-claim`], [/study-claim - Thorough Evidence Collection], [**Please collect more evidence of this claim through thorough study:**], [P:Y E:N U:N O:N I:Y W:N], [311],
  [`/study`], [/study - DocumentBuilder Study Gym], [**Purpose:** Scientific method-based learning system for discovering DocumentBuilder capabilities], [P:N E:N U:N O:N I:Y W:N], [159],
  [`/sync`], [Sync], [**Sync documentation across files - ensure consistency.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [357],
  [`/take-your-time`], [Take Your Time], [**Purpose**: Encourage deliberate, careful thinking and analysis before proceeding with work.], [P:N E:N U:N O:Y I:Y W:Y], [197],
  [`/tell-story`], [Tell Story], [**Generate a narrative PDF from story input using TheOracle, Storyteller, and TavernKeeper.**], [P:Y E:N U:N O:Y I:Y W:Y], [163],
  [`/thank-you`], [Thank You], [**Express gratitude and appreciation to your AI assistant.**], [P:Y E:N U:N O:N I:Y W:Y], [161],
  [`/the-archivist`], [/the-archivist - Daily PDF Archive & Morning Report], [**The Archivist - A Being who keeps things tidy. Minimal effort, maximum results.**], [P:Y E:N U:N O:N I:Y W:N], [216],
  [`/think`], [Think], [**Purpose**: Initialize all thinking and cognitive enhancement tools to kick thinking into high gear.], [P:N E:Y U:N O:Y I:Y W:N], [309],
  [`/todos`], [Todos], [**Todo management and tracking - manage tasks.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [382],
  [`/try-again`], [/try-again - Retry with Adjustments], [**Retries the last operation or command that failed, with intelligent adjustments based on what went wrong.**], [P:Y E:N U:N O:N I:Y W:Y], [293],
  [`/verify`], [Verify], [**Lightweight diagnostic verification with traceable evidence.**], [P:Y E:Y U:N O:Y I:N W:N], [355],
  [`/version-bake`], [Version-Bake], [**Complete quality workflow: reflect → run-it → improve → check-assumptions → verify → hypothesis → prove-it**], [P:Y E:Y U:N O:N I:Y W:Y], [429],
  [`/visualize`], [Visualize], [**Create a quick interactive browser UI to visualize current state and get visual insight.**], [P:Y E:Y U:Y O:Y I:Y W:Y], [377],
  [`/waft-boot`], [WAFT Boot], [**Kernel boot sequence - Initialize WAFT Kernel and perform initial status check.**], [P:Y E:N U:N O:N I:Y W:Y], [195],
  [`/waft-docs`], [WAFT Docs], [**Complete document generation workflow: field guides, booklets, printer-friendly versions, session summaries, and redaction tools.**], [P:Y E:N U:N O:N I:Y W:Y], [495],
  [`/waft-self-study`], [WAFT Self-Study], [**Self-monitoring and iterative study system using the proof methodology.**], [P:Y E:N U:N O:N I:Y W:N], [279],
  [`/waft-status`], [WAFT Status], [**Self-aware system status check with documentation generation at multiple complexity levels.**], [P:Y E:N U:N O:N I:Y W:Y], [596],
  [`/within-reason`], [/within-reason - Special Character Escaping for PDF Titles], [**Purpose:** Ensure any special character can be rendered properly in PDF titles (within reason).], [P:N E:N U:N O:N I:Y W:N], [203],
  [`/work-efforts`], [Work Efforts], [**Generate an interactive HTML dashboard with polymorphic action buttons for work efforts.**], [P:Y E:N U:N O:N I:Y W:N], [239],
  [`/worldbuild`], [/worldbuild - Worldbuilding Document Creator], [**Purpose:** Create compelling worldbuilding documents (fantasy or factual) with Foundation/TM formatting elements], [P:N E:N U:Y O:N I:Y W:N], [160],
)