"""
WAFT Reflection System
======================

A system for WAFT to observe, document, and improve itself.

Philosophy:
-----------
A system that documents itself creates a feedback loop:
1. WAFT generates documents
2. Those documents describe WAFT's architecture
3. That documentation informs future development
4. WAFT documents its own changes
5. The cycle continues

This is RECURSIVE SELF-IMPROVEMENT through documentation.

The Reflection Algorithm:
------------------------
1. OBSERVE - What does the system currently do?
2. DOCUMENT - Write clear documentation of current state
3. ANALYZE - What could be improved?
4. PROPOSE - Suggest enhancements based on documentation gaps
5. IMPLEMENT - Make changes
6. REFLECT - Document what changed and why

This creates a LIVING DOCUMENTATION SYSTEM that grows with the codebase.
"""

from pathlib import Path
from typing import List, Dict, Optional, Callable
from dataclasses import dataclass, field
import datetime
import json
import ast
import inspect


@dataclass
class Observation:
    """An observation about the codebase."""

    timestamp: str
    component: str  # Which part of WAFT
    observation: str  # What was observed
    documentation_status: str  # "documented", "undocumented", "outdated"
    priority: str = "medium"  # "low", "medium", "high", "critical"
    suggested_action: Optional[str] = None


@dataclass
class DocumentationGap:
    """A gap in documentation that should be filled."""

    component: str
    gap_type: str  # "missing", "incomplete", "outdated", "unclear"
    description: str
    current_state: str  # What exists now
    desired_state: str  # What should exist
    priority: str = "medium"


@dataclass
class ReflectionReport:
    """A report generated by the reflection system."""

    timestamp: str
    observations: List[Observation] = field(default_factory=list)
    gaps: List[DocumentationGap] = field(default_factory=list)
    recommendations: List[str] = field(default_factory=list)
    metrics: Dict[str, any] = field(default_factory=dict)


class ReflectionSystem:
    """
    WAFT's self-reflection and documentation system.

    This system observes WAFT's codebase, identifies documentation gaps,
    and helps maintain clear, current, consistent documentation.

    The Four Cs of Documentation:
    - CLEAR: Easy to understand
    - CLEAN: Well-organized
    - CURRENT: Up-to-date
    - CONSISTENT: Unified style/format

    Example:
        reflector = ReflectionSystem(waft_root=Path("src/waft"))

        # Observe current state
        report = reflector.reflect()

        # Generate documentation for gaps
        reflector.document_gaps(report)

        # Create self-documentation
        reflector.generate_architecture_doc()
    """

    def __init__(self, waft_root: Path):
        self.waft_root = waft_root
        self.observations = []
        self.documentation_history = []

    def observe_component(self, component_path: Path) -> List[Observation]:
        """
        Observe a component and identify documentation needs.

        Args:
            component_path: Path to Python file to observe

        Returns:
            List of observations
        """
        observations = []

        if not component_path.exists():
            return observations

        # Read source code
        source = component_path.read_text()

        try:
            tree = ast.parse(source)

            # Observe module docstring
            module_docstring = ast.get_docstring(tree)
            if not module_docstring:
                observations.append(Observation(
                    timestamp=datetime.datetime.now().isoformat(),
                    component=component_path.name,
                    observation="Module missing docstring",
                    documentation_status="undocumented",
                    priority="high",
                    suggested_action="Add module-level docstring explaining purpose"
                ))

            # Observe classes
            for node in ast.walk(tree):
                if isinstance(node, ast.ClassDef):
                    class_docstring = ast.get_docstring(node)
                    if not class_docstring:
                        observations.append(Observation(
                            timestamp=datetime.datetime.now().isoformat(),
                            component=f"{component_path.name}::{node.name}",
                            observation=f"Class {node.name} missing docstring",
                            documentation_status="undocumented",
                            priority="medium",
                            suggested_action=f"Document {node.name} class: purpose, attributes, methods"
                        ))

                # Observe functions
                elif isinstance(node, ast.FunctionDef):
                    func_docstring = ast.get_docstring(node)
                    if not func_docstring and not node.name.startswith('_'):
                        observations.append(Observation(
                            timestamp=datetime.datetime.now().isoformat(),
                            component=f"{component_path.name}::{node.name}",
                            observation=f"Function {node.name} missing docstring",
                            documentation_status="undocumented",
                            priority="medium",
                            suggested_action=f"Document {node.name}: parameters, returns, behavior"
                        ))

        except SyntaxError:
            observations.append(Observation(
                timestamp=datetime.datetime.now().isoformat(),
                component=component_path.name,
                observation="Syntax error prevents analysis",
                documentation_status="error",
                priority="critical",
                suggested_action="Fix syntax errors before documenting"
            ))

        return observations

    def reflect(self) -> ReflectionReport:
        """
        Perform full system reflection.

        Observes all WAFT components and generates report.

        Returns:
            ReflectionReport with observations and recommendations
        """
        report = ReflectionReport(
            timestamp=datetime.datetime.now().isoformat()
        )

        print("🔍 WAFT Reflection System - Observing codebase...")
        print()

        # Observe all Python files in waft
        python_files = list(self.waft_root.glob("**/*.py"))
        print(f"Found {len(python_files)} Python files")

        for py_file in python_files:
            if py_file.name.startswith('__'):
                continue

            observations = self.observe_component(py_file)
            report.observations.extend(observations)

        # Identify documentation gaps
        report.gaps = self._identify_gaps(report.observations)

        # Generate recommendations
        report.recommendations = self._generate_recommendations(report)

        # Calculate metrics
        report.metrics = {
            "total_files": len(python_files),
            "total_observations": len(report.observations),
            "undocumented_count": sum(1 for obs in report.observations
                                     if obs.documentation_status == "undocumented"),
            "high_priority_count": sum(1 for obs in report.observations
                                      if obs.priority == "high"),
            "critical_count": sum(1 for obs in report.observations
                                 if obs.priority == "critical"),
            "documentation_coverage": self._calculate_coverage(report.observations)
        }

        return report

    def _identify_gaps(self, observations: List[Observation]) -> List[DocumentationGap]:
        """Identify documentation gaps from observations."""
        gaps = []

        # Group observations by component
        by_component = {}
        for obs in observations:
            component = obs.component.split("::")[0]
            if component not in by_component:
                by_component[component] = []
            by_component[component].append(obs)

        # Create gaps for components with multiple undocumented items
        for component, obs_list in by_component.items():
            undoc_count = sum(1 for obs in obs_list
                            if obs.documentation_status == "undocumented")

            if undoc_count >= 3:
                gaps.append(DocumentationGap(
                    component=component,
                    gap_type="missing",
                    description=f"Component has {undoc_count} undocumented items",
                    current_state="Partial or no documentation",
                    desired_state="Comprehensive documentation with examples",
                    priority="high"
                ))

        return gaps

    def _generate_recommendations(self, report: ReflectionReport) -> List[str]:
        """Generate recommendations based on report."""
        recommendations = []

        # Critical issues first
        critical_obs = [obs for obs in report.observations if obs.priority == "critical"]
        if critical_obs:
            recommendations.append(
                f"🚨 CRITICAL: Address {len(critical_obs)} critical issues immediately"
            )

        # Documentation coverage
        coverage = report.metrics.get("documentation_coverage", 0)
        if coverage < 50:
            recommendations.append(
                f"📚 Documentation coverage is {coverage:.1f}%. Target: 80%+"
            )
        elif coverage < 80:
            recommendations.append(
                f"📚 Documentation coverage is {coverage:.1f}%. Close to target (80%)"
            )
        else:
            recommendations.append(
                f"✅ Excellent documentation coverage: {coverage:.1f}%"
            )

        # Undocumented items
        undoc_count = report.metrics.get("undocumented_count", 0)
        if undoc_count > 10:
            recommendations.append(
                f"📝 {undoc_count} undocumented items. Consider documentation sprint."
            )

        # Component-specific recommendations
        if report.gaps:
            recommendations.append(
                f"🎯 Focus documentation effort on {len(report.gaps)} high-gap components"
            )

        return recommendations

    def _calculate_coverage(self, observations: List[Observation]) -> float:
        """Calculate documentation coverage percentage."""
        if not observations:
            return 100.0

        undocumented = sum(1 for obs in observations
                          if obs.documentation_status == "undocumented")
        total = len(observations)

        return ((total - undocumented) / total) * 100

    def generate_reflection_report_doc(
        self,
        report: ReflectionReport,
        output_path: Path
    ) -> Path:
        """
        Generate a beautiful documentation report using WAFT's own system.

        This is WAFT documenting its own reflection. Meta!

        Args:
            report: ReflectionReport to document
            output_path: Where to save PDF

        Returns:
            Path to generated report
        """
        from src.waft.templates.code_documentation import generate_code_documentation

        # Build HTML content
        content = f"""
<h1>WAFT Reflection Report</h1>

<p>
This report was generated by WAFT's Reflection System, which observes the codebase
and identifies documentation needs. This is a living document - run reflection
regularly to maintain documentation quality.
</p>

<div class="note">
    <div class="note-title">Reflection Timestamp</div>
    {report.timestamp}
</div>

<h2>Executive Summary</h2>

<table class="param-table">
    <tr>
        <th>Metric</th>
        <th>Value</th>
    </tr>
    <tr>
        <td>Total Files Analyzed</td>
        <td>{report.metrics.get('total_files', 0)}</td>
    </tr>
    <tr>
        <td>Total Observations</td>
        <td>{report.metrics.get('total_observations', 0)}</td>
    </tr>
    <tr>
        <td>Undocumented Items</td>
        <td>{report.metrics.get('undocumented_count', 0)}</td>
    </tr>
    <tr>
        <td>Critical Issues</td>
        <td>{report.metrics.get('critical_count', 0)}</td>
    </tr>
    <tr>
        <td>Documentation Coverage</td>
        <td>{report.metrics.get('documentation_coverage', 0):.1f}%</td>
    </tr>
</table>

<h2>Recommendations</h2>

<ol>
"""
        for rec in report.recommendations:
            content += f"    <li>{rec}</li>\n"

        content += """
</ol>

<h2>Documentation Gaps</h2>

<p>
These components require focused documentation effort:
</p>
"""

        for gap in report.gaps:
            priority_color = {
                "critical": "#f44336",
                "high": "#ff9800",
                "medium": "#2196f3",
                "low": "#4caf50"
            }.get(gap.priority, "#666")

            content += f"""
<div class="warning" style="border-left-color: {priority_color};">
    <div class="warning-title" style="color: {priority_color};">{gap.component}</div>
    <p><strong>Gap Type:</strong> {gap.gap_type}</p>
    <p><strong>Description:</strong> {gap.description}</p>
    <p><strong>Current State:</strong> {gap.current_state}</p>
    <p><strong>Desired State:</strong> {gap.desired_state}</p>
    <p><strong>Priority:</strong> {gap.priority.upper()}</p>
</div>
"""

        content += """
<h2>Detailed Observations</h2>

<p>
Individual observations ordered by priority:
</p>
"""

        # Group observations by priority
        by_priority = {"critical": [], "high": [], "medium": [], "low": []}
        for obs in report.observations:
            by_priority[obs.priority].append(obs)

        for priority in ["critical", "high", "medium", "low"]:
            obs_list = by_priority[priority]
            if not obs_list:
                continue

            content += f"<h3>{priority.upper()} Priority ({len(obs_list)} items)</h3>\n"

            for obs in obs_list[:20]:  # Limit to first 20 per priority
                content += f"""
<div class="api-function">
    <div class="api-signature">{obs.component}</div>
    <div class="api-description">
        <p><strong>Observation:</strong> {obs.observation}</p>
        <p><strong>Status:</strong> {obs.documentation_status}</p>
        {f'<p><strong>Suggested Action:</strong> {obs.suggested_action}</p>' if obs.suggested_action else ''}
    </div>
</div>
"""

        content += """
<h2>Next Steps</h2>

<div class="tip">
    <div class="tip-title">Maintaining Documentation</div>
    <ol>
        <li>Run reflection regularly (weekly or after major changes)</li>
        <li>Address critical and high-priority observations first</li>
        <li>Set documentation coverage target (recommend 80%+)</li>
        <li>Use WAFT's code_documentation template for new docs</li>
        <li>Keep documentation close to code (docstrings)</li>
        <li>Document WHY, not just WHAT</li>
    </ol>
</div>

<h2>The Reflection Loop</h2>

<div class="diagram">
┌─────────────────────────────────────────────┐
│  1. OBSERVE                                  │
│     └─ Scan codebase for doc gaps          │
│                                              │
│  2. DOCUMENT                                 │
│     └─ Generate this reflection report      │
│                                              │
│  3. ANALYZE                                  │
│     └─ Identify high-priority gaps          │
│                                              │
│  4. IMPLEMENT                                │
│     └─ Write missing documentation          │
│                                              │
│  5. REFLECT                                  │
│     └─ Run observation again                │
│                                              │
│  6. REPEAT                                   │
│     └─ Documentation is never "done"        │
└─────────────────────────────────────────────┘
</div>

<p style="margin-top: 0.5in; text-align: center; font-style: italic; color: #666;">
This report was generated by WAFT's Reflection System.<br>
WAFT documenting itself. Recursive self-improvement through documentation.
</p>
        """

        # Generate using code documentation template
        return generate_code_documentation(
            title="WAFT Reflection Report",
            content=content,
            output_path=output_path,
            subtitle="Self-Observation and Documentation Analysis",
            project="WAFT",
            version="1.0",
            author="WAFT Reflection System",
            date=datetime.datetime.now().strftime("%B %d, %Y")
        )

    def generate_architecture_doc(self, output_path: Path) -> Path:
        """
        Generate comprehensive WAFT architecture documentation.

        This is WAFT documenting its own structure.

        Args:
            output_path: Where to save architecture doc

        Returns:
            Path to generated documentation
        """
        from src.waft.templates.code_documentation import generate_code_documentation

        # Scan WAFT directory structure
        templates = list((self.waft_root / "templates").glob("*.py"))
        core_files = [f for f in self.waft_root.glob("*.py") if not f.name.startswith('__')]

        content = """
<h1>WAFT System Architecture</h1>

<p>
WAFT (Document Generation Framework) is a pure-Python system for generating
professional documents from templates. This document describes the architecture,
components, and design philosophy.
</p>

<div class="note">
    <div class="note-title">Meta-Documentation</div>
    This documentation was generated BY WAFT, ABOUT WAFT, USING WAFT.
    It's a demonstration of the system documenting itself - recursive
    self-documentation.
</div>

<h2>System Overview</h2>

<p>
WAFT provides a flexible template-based document generation system with:
</p>

<ul>
    <li>12+ professional document templates</li>
    <li>WeasyPrint-based PDF generation</li>
    <li>Jinja2 templating engine</li>
    <li>Binder system for multi-document collections</li>
    <li>Reflection system for self-documentation</li>
</ul>

<h2>Architecture Diagram</h2>

<div class="diagram">
┌────────────────────────────────────────────────────────┐
│                    USER CODE                            │
│  (Your application using WAFT)                         │
└─────────────────┬──────────────────────────────────────┘
                  │
                  ▼
┌────────────────────────────────────────────────────────┐
│              WAFT TEMPLATE LAYER                        │
│                                                         │
│  ┌─────────────┐  ┌─────────────┐  ┌─────────────┐   │
│  │  Academic   │  │  Business   │  │  Creative   │   │
│  │  Templates  │  │  Templates  │  │  Templates  │   │
│  └─────────────┘  └─────────────┘  └─────────────┘   │
│                                                         │
│  ┌─────────────┐  ┌─────────────┐  ┌─────────────┐   │
│  │ Technical   │  │ Operational │  │  Narrative  │   │
│  │  Templates  │  │  Templates  │  │  Templates  │   │
│  └─────────────┘  └─────────────┘  └─────────────┘   │
└─────────────────┬──────────────────────────────────────┘
                  │
                  ▼
┌────────────────────────────────────────────────────────┐
│               WAFT CORE LAYER                           │
│                                                         │
│  ┌──────────────────────────────────────────────────┐ │
│  │  Binder System (binder.py)                       │ │
│  │  - Assemble multi-document collections          │ │
│  │  - Generate covers, TOC, dividers                │ │
│  └──────────────────────────────────────────────────┘ │
│                                                         │
│  ┌──────────────────────────────────────────────────┐ │
│  │  Reflection System (reflection.py)               │ │
│  │  - Self-observation                              │ │
│  │  - Documentation gap analysis                    │ │
│  │  - Architecture documentation                    │ │
│  └──────────────────────────────────────────────────┘ │
│                                                         │
│  ┌──────────────────────────────────────────────────┐ │
│  │  Foundation (foundation.py)                      │ │
│  │  - DocumentEngine base classes                   │ │
│  │  - Section, Paragraph, List primitives           │ │
│  └──────────────────────────────────────────────────┘ │
└─────────────────┬──────────────────────────────────────┘
                  │
                  ▼
┌────────────────────────────────────────────────────────┐
│            EXTERNAL DEPENDENCIES                        │
│                                                         │
│  ┌──────────────┐  ┌──────────────┐  ┌─────────────┐ │
│  │  WeasyPrint  │  │    Jinja2    │  │   pypdf     │ │
│  │  (PDF gen)   │  │ (Templates)  │  │  (Merging)  │ │
│  └──────────────┘  └──────────────┘  └─────────────┘ │
└────────────────────────────────────────────────────────┘
</div>

<h2>Core Components</h2>

<h3>1. Foundation Layer</h3>

<div class="api-function">
    <div class="api-signature">foundation.py</div>
    <div class="api-description">
        <p>Base classes for document generation:</p>
        <ul>
            <li><code>DocumentEngine</code> - Main document class</li>
            <li><code>Section</code> - Document sections</li>
            <li><code>Paragraph</code>, <code>List</code> - Content blocks</li>
            <li><code>Exporter</code> - PDF/HTML/Markdown export</li>
        </ul>
    </div>
</div>

<h3>2. Template Layer</h3>

<p>
WAFT includes 12 professional templates:
</p>

<table class="param-table">
    <tr>
        <th>Template</th>
        <th>Use Case</th>
        <th>File</th>
    </tr>
"""

        template_info = [
            ("Simple Scientific", "Academic papers, research", "simple_scientific.py"),
            ("Field Guide", "Operational manuals, survival guides", "field_guide.py"),
            ("TM Report", "Corporate reports, analysis", "tm_report.py"),
            ("Lab Notes", "Research logs, experiments", "lab_notes.py"),
            ("Personal Memo", "Staff communications, notes", "personal_memo.py"),
            ("Eldritch Journal", "Horror, madness narratives", "eldritch_journal.py"),
            ("Screenplay", "Film/TV scripts", "screenplay.py"),
            ("Heartfelt Letter", "Personal letters, emotional", "heartfelt_letter.py"),
            ("Invoice/Contract", "Business documents, invoices", "invoice_contract.py"),
            ("Code Documentation", "Technical docs, API refs", "code_documentation.py"),
            ("Children's Storybook", "Kids' books, whimsical", "storybook.py"),
            ("Newspaper", "News front pages, media", "newspaper.py"),
        ]

        for name, use_case, file in template_info:
            content += f"""
    <tr>
        <td><strong>{name}</strong></td>
        <td>{use_case}</td>
        <td><code>{file}</code></td>
    </tr>
"""

        content += """
</table>

<h3>3. Binder System</h3>

<div class="api-function">
    <div class="api-signature">binder.py - Binder class</div>
    <div class="api-description">
        <p>Assembles multiple documents into cohesive collections:</p>
        <ul>
            <li>Cover page generation (4 styles)</li>
            <li>Table of contents</li>
            <li>Section dividers</li>
            <li>Document merging</li>
            <li>Front/back matter support</li>
        </ul>
    </div>
</div>

<h3>4. Reflection System</h3>

<div class="api-function">
    <div class="api-signature">reflection.py - ReflectionSystem class</div>
    <div class="api-description">
        <p>Self-observation and documentation maintenance:</p>
        <ul>
            <li>Scans codebase for documentation gaps</li>
            <li>Generates reflection reports</li>
            <li>Calculates documentation coverage</li>
            <li>Provides improvement recommendations</li>
        </ul>
    </div>
</div>

<h2>Design Philosophy</h2>

<h3>The Four Cs</h3>

<div class="tip">
    <div class="tip-title">Documentation Principles</div>
    <ol>
        <li><strong>CLEAR</strong> - Easy to understand, unambiguous</li>
        <li><strong>CLEAN</strong> - Well-organized, logical structure</li>
        <li><strong>CURRENT</strong> - Up-to-date, reflects reality</li>
        <li><strong>CONSISTENT</strong> - Unified style and format</li>
    </ol>
</div>

<h3>Template Design</h3>

<p>
All WAFT templates follow these principles:
</p>

<ul>
    <li><strong>HTML/CSS-based</strong> - Leverages web technology for layout</li>
    <li><strong>Customizable</strong> - Colors, fonts, spacing all configurable</li>
    <li><strong>Print-ready</strong> - Professional PDF output</li>
    <li><strong>Fast</strong> - Generate documents in &lt; 1 second</li>
    <li><strong>Pure Python</strong> - No external compilers (LaTeX, etc.)</li>
</ul>

<h2>Usage Patterns</h2>

<h3>Basic Document Generation</h3>

<pre><code>from src.waft.templates.simple_scientific import generate_simple_scientific_document

# Generate a scientific paper
generate_simple_scientific_document(
    title="My Research Paper",
    content="&lt;h2&gt;Introduction&lt;/h2&gt;&lt;p&gt;...&lt;/p&gt;",
    output_path=Path("paper.pdf"),
    authors=["Dr. Smith"],
    abstract="This paper explores..."
)
</code></pre>

<h3>Creating a Binder</h3>

<pre><code>from src.waft.binder import Binder, DocumentEntry

# Create binder
binder = Binder(
    title="Project Documentation",
    subtitle="Complete Reference"
)

# Add section
tab1 = binder.add_section("Getting Started")
tab1.add_document(DocumentEntry(
    path=Path("intro.pdf"),
    title="Introduction"
))

# Generate
binder.generate(Path("complete_docs.pdf"))
</code></pre>

<h3>Running Reflection</h3>

<pre><code>from src.waft.reflection import ReflectionSystem

# Create reflector
reflector = ReflectionSystem(waft_root=Path("src/waft"))

# Observe codebase
report = reflector.reflect()

# Generate documentation report
reflector.generate_reflection_report_doc(
    report=report,
    output_path=Path("reflection_report.pdf")
)
</code></pre>

<h2>Future Enhancements</h2>

<div class="note">
    <div class="note-title">Roadmap</div>
    <ul>
        <li>MathJax integration for LaTeX equations</li>
        <li>Citation management (BibTeX support)</li>
        <li>Cross-reference system (Figure 3, Table 2)</li>
        <li>Syntax highlighting with Pygments</li>
        <li>Multi-format export (DOCX, EPUB)</li>
        <li>Template marketplace/sharing</li>
    </ul>
</div>

<h2>Conclusion</h2>

<p>
WAFT is a flexible, powerful document generation system built on modern web
technologies. Its template-based architecture makes it easy to create professional
documents for any use case - from academic papers to horror stories to business
invoices.
</p>

<p>
The addition of the Binder and Reflection systems creates a RECURSIVE DOCUMENTATION
LOOP: WAFT documents projects, those projects include WAFT's own development, and
that documentation informs future WAFT improvements.
</p>

<p style="font-style: italic; text-align: center; margin-top: 0.5in;">
A system that documents itself can observe itself improving.
</p>
        """

        return generate_code_documentation(
            title="WAFT System Architecture",
            content=content,
            output_path=output_path,
            subtitle="Complete Technical Documentation",
            project="WAFT",
            version="1.0",
            author="WAFT Reflection System",
            date=datetime.datetime.now().strftime("%B %d, %Y")
        )


# Example usage functions

def run_reflection_example():
    """Example: Run reflection and generate report."""
    reflector = ReflectionSystem(waft_root=Path("src/waft"))

    print("Running WAFT reflection...")
    report = reflector.reflect()

    print()
    print("=" * 70)
    print("REFLECTION REPORT SUMMARY")
    print("=" * 70)
    print()

    for key, value in report.metrics.items():
        print(f"{key}: {value}")

    print()
    print("Recommendations:")
    for rec in report.recommendations:
        print(f"  {rec}")

    print()
    print("Generating reflection report PDF...")

    report_path = Path("_work_efforts/WAFT_Reflection_Report.pdf")
    reflector.generate_reflection_report_doc(report, report_path)

    print(f"✓ Report saved: {report_path}")

    return report


def generate_architecture_doc_example():
    """Example: Generate WAFT architecture documentation."""
    reflector = ReflectionSystem(waft_root=Path("src/waft"))

    print("Generating WAFT architecture documentation...")

    arch_path = Path("_work_efforts/WAFT_Architecture.pdf")
    reflector.generate_architecture_doc(arch_path)

    print(f"✓ Architecture doc saved: {arch_path}")

    return arch_path
